// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: api/rsm/rsm.proto

package rsmpb

import (
	kvpb "github.com/DecarbonizedGlucose/rkv/api/kvrpc/kvpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Command struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Client_ID  string                 `protobuf:"bytes,1,opt,name=client_ID,json=clientID,proto3" json:"client_ID,omitempty"`
	Request_ID string                 `protobuf:"bytes,2,opt,name=request_ID,json=requestID,proto3" json:"request_ID,omitempty"`
	// Types that are valid to be assigned to KVRequest:
	//
	//	*Command_GetRequest
	//	*Command_PutRequest
	//	*Command_DeleteRequest
	//	*Command_AppendRequest
	//	*Command_CasRequest
	KVRequest     isCommand_KVRequest `protobuf_oneof:"KVRequest"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_api_rsm_rsm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_api_rsm_rsm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_api_rsm_rsm_proto_rawDescGZIP(), []int{0}
}

func (x *Command) GetClient_ID() string {
	if x != nil {
		return x.Client_ID
	}
	return ""
}

func (x *Command) GetRequest_ID() string {
	if x != nil {
		return x.Request_ID
	}
	return ""
}

func (x *Command) GetKVRequest() isCommand_KVRequest {
	if x != nil {
		return x.KVRequest
	}
	return nil
}

func (x *Command) GetGetRequest() *kvpb.GetRequest {
	if x != nil {
		if x, ok := x.KVRequest.(*Command_GetRequest); ok {
			return x.GetRequest
		}
	}
	return nil
}

func (x *Command) GetPutRequest() *kvpb.PutRequest {
	if x != nil {
		if x, ok := x.KVRequest.(*Command_PutRequest); ok {
			return x.PutRequest
		}
	}
	return nil
}

func (x *Command) GetDeleteRequest() *kvpb.DeleteRequest {
	if x != nil {
		if x, ok := x.KVRequest.(*Command_DeleteRequest); ok {
			return x.DeleteRequest
		}
	}
	return nil
}

func (x *Command) GetAppendRequest() *kvpb.AppendRequest {
	if x != nil {
		if x, ok := x.KVRequest.(*Command_AppendRequest); ok {
			return x.AppendRequest
		}
	}
	return nil
}

func (x *Command) GetCasRequest() *kvpb.CASRequest {
	if x != nil {
		if x, ok := x.KVRequest.(*Command_CasRequest); ok {
			return x.CasRequest
		}
	}
	return nil
}

type isCommand_KVRequest interface {
	isCommand_KVRequest()
}

type Command_GetRequest struct {
	GetRequest *kvpb.GetRequest `protobuf:"bytes,3,opt,name=get_request,json=getRequest,proto3,oneof"`
}

type Command_PutRequest struct {
	PutRequest *kvpb.PutRequest `protobuf:"bytes,4,opt,name=put_request,json=putRequest,proto3,oneof"`
}

type Command_DeleteRequest struct {
	DeleteRequest *kvpb.DeleteRequest `protobuf:"bytes,5,opt,name=delete_request,json=deleteRequest,proto3,oneof"`
}

type Command_AppendRequest struct {
	AppendRequest *kvpb.AppendRequest `protobuf:"bytes,6,opt,name=append_request,json=appendRequest,proto3,oneof"`
}

type Command_CasRequest struct {
	CasRequest *kvpb.CASRequest `protobuf:"bytes,7,opt,name=cas_request,json=casRequest,proto3,oneof"` // and, the multi-get request, TODO
}

func (*Command_GetRequest) isCommand_KVRequest() {}

func (*Command_PutRequest) isCommand_KVRequest() {}

func (*Command_DeleteRequest) isCommand_KVRequest() {}

func (*Command_AppendRequest) isCommand_KVRequest() {}

func (*Command_CasRequest) isCommand_KVRequest() {}

var File_api_rsm_rsm_proto protoreflect.FileDescriptor

const file_api_rsm_rsm_proto_rawDesc = "" +
	"\n" +
	"\x11api/rsm/rsm.proto\x12\x03rsm\x1a\x12api/kvrpc/kv.proto\"\xf2\x02\n" +
	"\aCommand\x12\x1b\n" +
	"\tclient_ID\x18\x01 \x01(\tR\bclientID\x12\x1d\n" +
	"\n" +
	"request_ID\x18\x02 \x01(\tR\trequestID\x124\n" +
	"\vget_request\x18\x03 \x01(\v2\x11.kvrpc.GetRequestH\x00R\n" +
	"getRequest\x124\n" +
	"\vput_request\x18\x04 \x01(\v2\x11.kvrpc.PutRequestH\x00R\n" +
	"putRequest\x12=\n" +
	"\x0edelete_request\x18\x05 \x01(\v2\x14.kvrpc.DeleteRequestH\x00R\rdeleteRequest\x12=\n" +
	"\x0eappend_request\x18\x06 \x01(\v2\x14.kvrpc.AppendRequestH\x00R\rappendRequest\x124\n" +
	"\vcas_request\x18\a \x01(\v2\x11.kvrpc.CASRequestH\x00R\n" +
	"casRequestB\v\n" +
	"\tKVRequestB2Z0github.com/DecarbonizedGlucose/rkv/api/rsm/rsmpbb\x06proto3"

var (
	file_api_rsm_rsm_proto_rawDescOnce sync.Once
	file_api_rsm_rsm_proto_rawDescData []byte
)

func file_api_rsm_rsm_proto_rawDescGZIP() []byte {
	file_api_rsm_rsm_proto_rawDescOnce.Do(func() {
		file_api_rsm_rsm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_rsm_rsm_proto_rawDesc), len(file_api_rsm_rsm_proto_rawDesc)))
	})
	return file_api_rsm_rsm_proto_rawDescData
}

var file_api_rsm_rsm_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_rsm_rsm_proto_goTypes = []any{
	(*Command)(nil),            // 0: rsm.Command
	(*kvpb.GetRequest)(nil),    // 1: kvrpc.GetRequest
	(*kvpb.PutRequest)(nil),    // 2: kvrpc.PutRequest
	(*kvpb.DeleteRequest)(nil), // 3: kvrpc.DeleteRequest
	(*kvpb.AppendRequest)(nil), // 4: kvrpc.AppendRequest
	(*kvpb.CASRequest)(nil),    // 5: kvrpc.CASRequest
}
var file_api_rsm_rsm_proto_depIdxs = []int32{
	1, // 0: rsm.Command.get_request:type_name -> kvrpc.GetRequest
	2, // 1: rsm.Command.put_request:type_name -> kvrpc.PutRequest
	3, // 2: rsm.Command.delete_request:type_name -> kvrpc.DeleteRequest
	4, // 3: rsm.Command.append_request:type_name -> kvrpc.AppendRequest
	5, // 4: rsm.Command.cas_request:type_name -> kvrpc.CASRequest
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_rsm_rsm_proto_init() }
func file_api_rsm_rsm_proto_init() {
	if File_api_rsm_rsm_proto != nil {
		return
	}
	file_api_rsm_rsm_proto_msgTypes[0].OneofWrappers = []any{
		(*Command_GetRequest)(nil),
		(*Command_PutRequest)(nil),
		(*Command_DeleteRequest)(nil),
		(*Command_AppendRequest)(nil),
		(*Command_CasRequest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_rsm_rsm_proto_rawDesc), len(file_api_rsm_rsm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_rsm_rsm_proto_goTypes,
		DependencyIndexes: file_api_rsm_rsm_proto_depIdxs,
		MessageInfos:      file_api_rsm_rsm_proto_msgTypes,
	}.Build()
	File_api_rsm_rsm_proto = out.File
	file_api_rsm_rsm_proto_goTypes = nil
	file_api_rsm_rsm_proto_depIdxs = nil
}
