// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: api/raftrpc/persistence.proto

package raftrpcpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RaftPersistence_InstallSnapshot_FullMethodName = "/raftrpc.RaftPersistence/InstallSnapshot"
)

// RaftPersistenceClient is the client API for RaftPersistence service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RaftPersistenceClient interface {
	InstallSnapshot(ctx context.Context, in *InstallSnapshotRequest, opts ...grpc.CallOption) (*InstallSnapshotResponse, error)
}

type raftPersistenceClient struct {
	cc grpc.ClientConnInterface
}

func NewRaftPersistenceClient(cc grpc.ClientConnInterface) RaftPersistenceClient {
	return &raftPersistenceClient{cc}
}

func (c *raftPersistenceClient) InstallSnapshot(ctx context.Context, in *InstallSnapshotRequest, opts ...grpc.CallOption) (*InstallSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstallSnapshotResponse)
	err := c.cc.Invoke(ctx, RaftPersistence_InstallSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RaftPersistenceServer is the server API for RaftPersistence service.
// All implementations must embed UnimplementedRaftPersistenceServer
// for forward compatibility.
type RaftPersistenceServer interface {
	InstallSnapshot(context.Context, *InstallSnapshotRequest) (*InstallSnapshotResponse, error)
	mustEmbedUnimplementedRaftPersistenceServer()
}

// UnimplementedRaftPersistenceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRaftPersistenceServer struct{}

func (UnimplementedRaftPersistenceServer) InstallSnapshot(context.Context, *InstallSnapshotRequest) (*InstallSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InstallSnapshot not implemented")
}
func (UnimplementedRaftPersistenceServer) mustEmbedUnimplementedRaftPersistenceServer() {}
func (UnimplementedRaftPersistenceServer) testEmbeddedByValue()                         {}

// UnsafeRaftPersistenceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RaftPersistenceServer will
// result in compilation errors.
type UnsafeRaftPersistenceServer interface {
	mustEmbedUnimplementedRaftPersistenceServer()
}

func RegisterRaftPersistenceServer(s grpc.ServiceRegistrar, srv RaftPersistenceServer) {
	// If the following call panics, it indicates UnimplementedRaftPersistenceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RaftPersistence_ServiceDesc, srv)
}

func _RaftPersistence_InstallSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstallSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftPersistenceServer).InstallSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RaftPersistence_InstallSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftPersistenceServer).InstallSnapshot(ctx, req.(*InstallSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RaftPersistence_ServiceDesc is the grpc.ServiceDesc for RaftPersistence service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RaftPersistence_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "raftrpc.RaftPersistence",
	HandlerType: (*RaftPersistenceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InstallSnapshot",
			Handler:    _RaftPersistence_InstallSnapshot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/raftrpc/persistence.proto",
}
