// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: api/raftrpc/snapshot.proto

package raftrpcpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RaftSnapshot_InstallSnapshot_FullMethodName = "/raftrpc.RaftSnapshot/InstallSnapshot"
)

// RaftSnapshotClient is the client API for RaftSnapshot service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RaftSnapshotClient interface {
	InstallSnapshot(ctx context.Context, in *InstallSnapshotRequest, opts ...grpc.CallOption) (*InstallSnapshotResponse, error)
}

type raftSnapshotClient struct {
	cc grpc.ClientConnInterface
}

func NewRaftSnapshotClient(cc grpc.ClientConnInterface) RaftSnapshotClient {
	return &raftSnapshotClient{cc}
}

func (c *raftSnapshotClient) InstallSnapshot(ctx context.Context, in *InstallSnapshotRequest, opts ...grpc.CallOption) (*InstallSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstallSnapshotResponse)
	err := c.cc.Invoke(ctx, RaftSnapshot_InstallSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RaftSnapshotServer is the server API for RaftSnapshot service.
// All implementations must embed UnimplementedRaftSnapshotServer
// for forward compatibility.
type RaftSnapshotServer interface {
	InstallSnapshot(context.Context, *InstallSnapshotRequest) (*InstallSnapshotResponse, error)
	mustEmbedUnimplementedRaftSnapshotServer()
}

// UnimplementedRaftSnapshotServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRaftSnapshotServer struct{}

func (UnimplementedRaftSnapshotServer) InstallSnapshot(context.Context, *InstallSnapshotRequest) (*InstallSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InstallSnapshot not implemented")
}
func (UnimplementedRaftSnapshotServer) mustEmbedUnimplementedRaftSnapshotServer() {}
func (UnimplementedRaftSnapshotServer) testEmbeddedByValue()                      {}

// UnsafeRaftSnapshotServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RaftSnapshotServer will
// result in compilation errors.
type UnsafeRaftSnapshotServer interface {
	mustEmbedUnimplementedRaftSnapshotServer()
}

func RegisterRaftSnapshotServer(s grpc.ServiceRegistrar, srv RaftSnapshotServer) {
	// If the following call panics, it indicates UnimplementedRaftSnapshotServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RaftSnapshot_ServiceDesc, srv)
}

func _RaftSnapshot_InstallSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstallSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftSnapshotServer).InstallSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RaftSnapshot_InstallSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftSnapshotServer).InstallSnapshot(ctx, req.(*InstallSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RaftSnapshot_ServiceDesc is the grpc.ServiceDesc for RaftSnapshot service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RaftSnapshot_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "raftrpc.RaftSnapshot",
	HandlerType: (*RaftSnapshotServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InstallSnapshot",
			Handler:    _RaftSnapshot_InstallSnapshot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/raftrpc/snapshot.proto",
}
