// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: api/raftrpc/snapshot.proto

package raftrpcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InstallSnapshotRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Term              int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId          int64                  `protobuf:"varint,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	LastIncludedIndex int64                  `protobuf:"varint,3,opt,name=last_included_index,json=lastIncludedIndex,proto3" json:"last_included_index,omitempty"`
	LastIncludedTerm  int64                  `protobuf:"varint,4,opt,name=last_included_term,json=lastIncludedTerm,proto3" json:"last_included_term,omitempty"`
	Data              []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InstallSnapshotRequest) Reset() {
	*x = InstallSnapshotRequest{}
	mi := &file_api_raftrpc_snapshot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallSnapshotRequest) ProtoMessage() {}

func (x *InstallSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_raftrpc_snapshot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallSnapshotRequest.ProtoReflect.Descriptor instead.
func (*InstallSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_api_raftrpc_snapshot_proto_rawDescGZIP(), []int{0}
}

func (x *InstallSnapshotRequest) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *InstallSnapshotRequest) GetLeaderId() int64 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *InstallSnapshotRequest) GetLastIncludedIndex() int64 {
	if x != nil {
		return x.LastIncludedIndex
	}
	return 0
}

func (x *InstallSnapshotRequest) GetLastIncludedTerm() int64 {
	if x != nil {
		return x.LastIncludedTerm
	}
	return 0
}

func (x *InstallSnapshotRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type InstallSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallSnapshotResponse) Reset() {
	*x = InstallSnapshotResponse{}
	mi := &file_api_raftrpc_snapshot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallSnapshotResponse) ProtoMessage() {}

func (x *InstallSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_raftrpc_snapshot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallSnapshotResponse.ProtoReflect.Descriptor instead.
func (*InstallSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_api_raftrpc_snapshot_proto_rawDescGZIP(), []int{1}
}

func (x *InstallSnapshotResponse) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

var File_api_raftrpc_snapshot_proto protoreflect.FileDescriptor

const file_api_raftrpc_snapshot_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/raftrpc/snapshot.proto\x12\araftrpc\"\xbb\x01\n" +
	"\x16InstallSnapshotRequest\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\x03R\bleaderId\x12.\n" +
	"\x13last_included_index\x18\x03 \x01(\x03R\x11lastIncludedIndex\x12,\n" +
	"\x12last_included_term\x18\x04 \x01(\x03R\x10lastIncludedTerm\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\"-\n" +
	"\x17InstallSnapshotResponse\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term2d\n" +
	"\fRaftSnapshot\x12T\n" +
	"\x0fInstallSnapshot\x12\x1f.raftrpc.InstallSnapshotRequest\x1a .raftrpc.InstallSnapshotResponseB:Z8github.com/DecarbonizedGlucose/rkv/api/raftrpc;raftrpcpbb\x06proto3"

var (
	file_api_raftrpc_snapshot_proto_rawDescOnce sync.Once
	file_api_raftrpc_snapshot_proto_rawDescData []byte
)

func file_api_raftrpc_snapshot_proto_rawDescGZIP() []byte {
	file_api_raftrpc_snapshot_proto_rawDescOnce.Do(func() {
		file_api_raftrpc_snapshot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_raftrpc_snapshot_proto_rawDesc), len(file_api_raftrpc_snapshot_proto_rawDesc)))
	})
	return file_api_raftrpc_snapshot_proto_rawDescData
}

var file_api_raftrpc_snapshot_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_raftrpc_snapshot_proto_goTypes = []any{
	(*InstallSnapshotRequest)(nil),  // 0: raftrpc.InstallSnapshotRequest
	(*InstallSnapshotResponse)(nil), // 1: raftrpc.InstallSnapshotResponse
}
var file_api_raftrpc_snapshot_proto_depIdxs = []int32{
	0, // 0: raftrpc.RaftSnapshot.InstallSnapshot:input_type -> raftrpc.InstallSnapshotRequest
	1, // 1: raftrpc.RaftSnapshot.InstallSnapshot:output_type -> raftrpc.InstallSnapshotResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_raftrpc_snapshot_proto_init() }
func file_api_raftrpc_snapshot_proto_init() {
	if File_api_raftrpc_snapshot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_raftrpc_snapshot_proto_rawDesc), len(file_api_raftrpc_snapshot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_raftrpc_snapshot_proto_goTypes,
		DependencyIndexes: file_api_raftrpc_snapshot_proto_depIdxs,
		MessageInfos:      file_api_raftrpc_snapshot_proto_msgTypes,
	}.Build()
	File_api_raftrpc_snapshot_proto = out.File
	file_api_raftrpc_snapshot_proto_goTypes = nil
	file_api_raftrpc_snapshot_proto_depIdxs = nil
}
