// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: rpc.proto

package rpcpb

import (
	kvpb "github.com/DecarbonizedGlucose/rkv/api/proto/pkg/kvpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_rpc_proto protoreflect.FileDescriptor

const file_rpc_proto_rawDesc = "" +
	"\n" +
	"\trpc.proto\x12\x05rpcpb\x1a\bkv.proto2\xf6\x01\n" +
	"\tKVService\x12*\n" +
	"\x03Put\x12\x10.kvpb.PutRequest\x1a\x11.kvpb.PutResponse\x123\n" +
	"\x06Delete\x12\x13.kvpb.DeleteRequest\x1a\x14.kvpb.DeleteResponse\x12*\n" +
	"\x03Get\x12\x10.kvpb.GetRequest\x1a\x11.kvpb.GetResponse\x120\n" +
	"\x05Range\x12\x12.kvpb.RangeRequest\x1a\x13.kvpb.RangeResponse\x12*\n" +
	"\x03Txn\x12\x10.kvpb.TxnRequest\x1a\x11.kvpb.TxnResponse2B\n" +
	"\fWatchService\x122\n" +
	"\x05Watch\x12\x12.kvpb.WatchRequest\x1a\x13.kvpb.WatchResponse0\x012\xe4\x01\n" +
	"\fLeaseService\x12?\n" +
	"\n" +
	"LeaseGrant\x12\x17.kvpb.LeaseGrantRequest\x1a\x18.kvpb.LeaseGrantResponse\x12B\n" +
	"\vLeaseRevoke\x12\x18.kvpb.LeaseRevokeRequest\x1a\x19.kvpb.LeaseRevokeResponse\x12O\n" +
	"\x0eLeaseKeepAlive\x12\x1b.kvpb.LeaseKeepAliveRequest\x1a\x1c.kvpb.LeaseKeepAliveResponse(\x010\x01B8Z6github.com/DecarbonizedGlucose/rkv/api/proto/pkg/rpcpbb\x06proto3"

var file_rpc_proto_goTypes = []any{
	(*kvpb.PutRequest)(nil),             // 0: kvpb.PutRequest
	(*kvpb.DeleteRequest)(nil),          // 1: kvpb.DeleteRequest
	(*kvpb.GetRequest)(nil),             // 2: kvpb.GetRequest
	(*kvpb.RangeRequest)(nil),           // 3: kvpb.RangeRequest
	(*kvpb.TxnRequest)(nil),             // 4: kvpb.TxnRequest
	(*kvpb.WatchRequest)(nil),           // 5: kvpb.WatchRequest
	(*kvpb.LeaseGrantRequest)(nil),      // 6: kvpb.LeaseGrantRequest
	(*kvpb.LeaseRevokeRequest)(nil),     // 7: kvpb.LeaseRevokeRequest
	(*kvpb.LeaseKeepAliveRequest)(nil),  // 8: kvpb.LeaseKeepAliveRequest
	(*kvpb.PutResponse)(nil),            // 9: kvpb.PutResponse
	(*kvpb.DeleteResponse)(nil),         // 10: kvpb.DeleteResponse
	(*kvpb.GetResponse)(nil),            // 11: kvpb.GetResponse
	(*kvpb.RangeResponse)(nil),          // 12: kvpb.RangeResponse
	(*kvpb.TxnResponse)(nil),            // 13: kvpb.TxnResponse
	(*kvpb.WatchResponse)(nil),          // 14: kvpb.WatchResponse
	(*kvpb.LeaseGrantResponse)(nil),     // 15: kvpb.LeaseGrantResponse
	(*kvpb.LeaseRevokeResponse)(nil),    // 16: kvpb.LeaseRevokeResponse
	(*kvpb.LeaseKeepAliveResponse)(nil), // 17: kvpb.LeaseKeepAliveResponse
}
var file_rpc_proto_depIdxs = []int32{
	0,  // 0: rpcpb.KVService.Put:input_type -> kvpb.PutRequest
	1,  // 1: rpcpb.KVService.Delete:input_type -> kvpb.DeleteRequest
	2,  // 2: rpcpb.KVService.Get:input_type -> kvpb.GetRequest
	3,  // 3: rpcpb.KVService.Range:input_type -> kvpb.RangeRequest
	4,  // 4: rpcpb.KVService.Txn:input_type -> kvpb.TxnRequest
	5,  // 5: rpcpb.WatchService.Watch:input_type -> kvpb.WatchRequest
	6,  // 6: rpcpb.LeaseService.LeaseGrant:input_type -> kvpb.LeaseGrantRequest
	7,  // 7: rpcpb.LeaseService.LeaseRevoke:input_type -> kvpb.LeaseRevokeRequest
	8,  // 8: rpcpb.LeaseService.LeaseKeepAlive:input_type -> kvpb.LeaseKeepAliveRequest
	9,  // 9: rpcpb.KVService.Put:output_type -> kvpb.PutResponse
	10, // 10: rpcpb.KVService.Delete:output_type -> kvpb.DeleteResponse
	11, // 11: rpcpb.KVService.Get:output_type -> kvpb.GetResponse
	12, // 12: rpcpb.KVService.Range:output_type -> kvpb.RangeResponse
	13, // 13: rpcpb.KVService.Txn:output_type -> kvpb.TxnResponse
	14, // 14: rpcpb.WatchService.Watch:output_type -> kvpb.WatchResponse
	15, // 15: rpcpb.LeaseService.LeaseGrant:output_type -> kvpb.LeaseGrantResponse
	16, // 16: rpcpb.LeaseService.LeaseRevoke:output_type -> kvpb.LeaseRevokeResponse
	17, // 17: rpcpb.LeaseService.LeaseKeepAlive:output_type -> kvpb.LeaseKeepAliveResponse
	9,  // [9:18] is the sub-list for method output_type
	0,  // [0:9] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_proto_init() }
func file_rpc_proto_init() {
	if File_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_proto_rawDesc), len(file_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_rpc_proto_goTypes,
		DependencyIndexes: file_rpc_proto_depIdxs,
	}.Build()
	File_rpc_proto = out.File
	file_rpc_proto_goTypes = nil
	file_rpc_proto_depIdxs = nil
}
