// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: api/kvrpc/kv.proto

package kvpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KVErrorCode int32

const (
	KVErrorCode_STATUS_UNSPECIFIED KVErrorCode = 0
	KVErrorCode_OK                 KVErrorCode = 1 // No error
	KVErrorCode_KEY_NOT_FOUND      KVErrorCode = 2 // ErrNoKey
	KVErrorCode_VERSION_MISMATCH   KVErrorCode = 3 // ErrWrongVersion / ErrVersionMismatch
	KVErrorCode_CONFLICT           KVErrorCode = 4 // ErrConflict (transaction conflict, CAS failure, etc)
	KVErrorCode_EXPIRED            KVErrorCode = 5 // ErrExpired
	KVErrorCode_OUTDATED           KVErrorCode = 6 // ErrOutdated
	KVErrorCode_INTERNAL           KVErrorCode = 7 // Internal Error
)

// Enum value maps for KVErrorCode.
var (
	KVErrorCode_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "OK",
		2: "KEY_NOT_FOUND",
		3: "VERSION_MISMATCH",
		4: "CONFLICT",
		5: "EXPIRED",
		6: "OUTDATED",
		7: "INTERNAL",
	}
	KVErrorCode_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"OK":                 1,
		"KEY_NOT_FOUND":      2,
		"VERSION_MISMATCH":   3,
		"CONFLICT":           4,
		"EXPIRED":            5,
		"OUTDATED":           6,
		"INTERNAL":           7,
	}
)

func (x KVErrorCode) Enum() *KVErrorCode {
	p := new(KVErrorCode)
	*p = x
	return p
}

func (x KVErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KVErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_kvrpc_kv_proto_enumTypes[0].Descriptor()
}

func (KVErrorCode) Type() protoreflect.EnumType {
	return &file_api_kvrpc_kv_proto_enumTypes[0]
}

func (x KVErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KVErrorCode.Descriptor instead.
func (KVErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_api_kvrpc_kv_proto_rawDescGZIP(), []int{0}
}

type RequestWithMeta struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Client_ID  string                 `protobuf:"bytes,1,opt,name=client_ID,json=clientID,proto3" json:"client_ID,omitempty"`
	Request_ID int64                  `protobuf:"varint,2,opt,name=request_ID,json=requestID,proto3" json:"request_ID,omitempty"`
	// Types that are valid to be assigned to KVRequest:
	//
	//	*RequestWithMeta_GetRequest
	//	*RequestWithMeta_PutRequest
	//	*RequestWithMeta_DeleteRequest
	//	*RequestWithMeta_AppendRequest
	//	*RequestWithMeta_CasRequest
	KVRequest     isRequestWithMeta_KVRequest `protobuf_oneof:"KVRequest"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestWithMeta) Reset() {
	*x = RequestWithMeta{}
	mi := &file_api_kvrpc_kv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestWithMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestWithMeta) ProtoMessage() {}

func (x *RequestWithMeta) ProtoReflect() protoreflect.Message {
	mi := &file_api_kvrpc_kv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestWithMeta.ProtoReflect.Descriptor instead.
func (*RequestWithMeta) Descriptor() ([]byte, []int) {
	return file_api_kvrpc_kv_proto_rawDescGZIP(), []int{0}
}

func (x *RequestWithMeta) GetClient_ID() string {
	if x != nil {
		return x.Client_ID
	}
	return ""
}

func (x *RequestWithMeta) GetRequest_ID() int64 {
	if x != nil {
		return x.Request_ID
	}
	return 0
}

func (x *RequestWithMeta) GetKVRequest() isRequestWithMeta_KVRequest {
	if x != nil {
		return x.KVRequest
	}
	return nil
}

func (x *RequestWithMeta) GetGetRequest() *GetRequest {
	if x != nil {
		if x, ok := x.KVRequest.(*RequestWithMeta_GetRequest); ok {
			return x.GetRequest
		}
	}
	return nil
}

func (x *RequestWithMeta) GetPutRequest() *PutRequest {
	if x != nil {
		if x, ok := x.KVRequest.(*RequestWithMeta_PutRequest); ok {
			return x.PutRequest
		}
	}
	return nil
}

func (x *RequestWithMeta) GetDeleteRequest() *DeleteRequest {
	if x != nil {
		if x, ok := x.KVRequest.(*RequestWithMeta_DeleteRequest); ok {
			return x.DeleteRequest
		}
	}
	return nil
}

func (x *RequestWithMeta) GetAppendRequest() *AppendRequest {
	if x != nil {
		if x, ok := x.KVRequest.(*RequestWithMeta_AppendRequest); ok {
			return x.AppendRequest
		}
	}
	return nil
}

func (x *RequestWithMeta) GetCasRequest() *CASRequest {
	if x != nil {
		if x, ok := x.KVRequest.(*RequestWithMeta_CasRequest); ok {
			return x.CasRequest
		}
	}
	return nil
}

type isRequestWithMeta_KVRequest interface {
	isRequestWithMeta_KVRequest()
}

type RequestWithMeta_GetRequest struct {
	GetRequest *GetRequest `protobuf:"bytes,3,opt,name=get_request,json=getRequest,proto3,oneof"`
}

type RequestWithMeta_PutRequest struct {
	PutRequest *PutRequest `protobuf:"bytes,4,opt,name=put_request,json=putRequest,proto3,oneof"`
}

type RequestWithMeta_DeleteRequest struct {
	DeleteRequest *DeleteRequest `protobuf:"bytes,5,opt,name=delete_request,json=deleteRequest,proto3,oneof"`
}

type RequestWithMeta_AppendRequest struct {
	AppendRequest *AppendRequest `protobuf:"bytes,6,opt,name=append_request,json=appendRequest,proto3,oneof"`
}

type RequestWithMeta_CasRequest struct {
	CasRequest *CASRequest `protobuf:"bytes,7,opt,name=cas_request,json=casRequest,proto3,oneof"`
}

func (*RequestWithMeta_GetRequest) isRequestWithMeta_KVRequest() {}

func (*RequestWithMeta_PutRequest) isRequestWithMeta_KVRequest() {}

func (*RequestWithMeta_DeleteRequest) isRequestWithMeta_KVRequest() {}

func (*RequestWithMeta_AppendRequest) isRequestWithMeta_KVRequest() {}

func (*RequestWithMeta_CasRequest) isRequestWithMeta_KVRequest() {}

type Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to KVResponse:
	//
	//	*Response_GetResponse
	//	*Response_PutResponse
	//	*Response_DeleteResponse
	//	*Response_AppendResponse
	//	*Response_CasResponse
	KVResponse    isResponse_KVResponse `protobuf_oneof:"KVResponse"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_api_kvrpc_kv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_kvrpc_kv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_api_kvrpc_kv_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetKVResponse() isResponse_KVResponse {
	if x != nil {
		return x.KVResponse
	}
	return nil
}

func (x *Response) GetGetResponse() *GetResponse {
	if x != nil {
		if x, ok := x.KVResponse.(*Response_GetResponse); ok {
			return x.GetResponse
		}
	}
	return nil
}

func (x *Response) GetPutResponse() *PutResponse {
	if x != nil {
		if x, ok := x.KVResponse.(*Response_PutResponse); ok {
			return x.PutResponse
		}
	}
	return nil
}

func (x *Response) GetDeleteResponse() *DeleteResponse {
	if x != nil {
		if x, ok := x.KVResponse.(*Response_DeleteResponse); ok {
			return x.DeleteResponse
		}
	}
	return nil
}

func (x *Response) GetAppendResponse() *AppendResponse {
	if x != nil {
		if x, ok := x.KVResponse.(*Response_AppendResponse); ok {
			return x.AppendResponse
		}
	}
	return nil
}

func (x *Response) GetCasResponse() *CASResponse {
	if x != nil {
		if x, ok := x.KVResponse.(*Response_CasResponse); ok {
			return x.CasResponse
		}
	}
	return nil
}

type isResponse_KVResponse interface {
	isResponse_KVResponse()
}

type Response_GetResponse struct {
	GetResponse *GetResponse `protobuf:"bytes,1,opt,name=get_response,json=getResponse,proto3,oneof"`
}

type Response_PutResponse struct {
	PutResponse *PutResponse `protobuf:"bytes,2,opt,name=put_response,json=putResponse,proto3,oneof"`
}

type Response_DeleteResponse struct {
	DeleteResponse *DeleteResponse `protobuf:"bytes,3,opt,name=delete_response,json=deleteResponse,proto3,oneof"`
}

type Response_AppendResponse struct {
	AppendResponse *AppendResponse `protobuf:"bytes,4,opt,name=append_response,json=appendResponse,proto3,oneof"`
}

type Response_CasResponse struct {
	CasResponse *CASResponse `protobuf:"bytes,5,opt,name=cas_response,json=casResponse,proto3,oneof"`
}

func (*Response_GetResponse) isResponse_KVResponse() {}

func (*Response_PutResponse) isResponse_KVResponse() {}

func (*Response_DeleteResponse) isResponse_KVResponse() {}

func (*Response_AppendResponse) isResponse_KVResponse() {}

func (*Response_CasResponse) isResponse_KVResponse() {}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_api_kvrpc_kv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_kvrpc_kv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_api_kvrpc_kv_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Version       uint64                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Status        KVErrorCode            `protobuf:"varint,3,opt,name=status,proto3,enum=kvrpc.KVErrorCode" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_api_kvrpc_kv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_kvrpc_kv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_api_kvrpc_kv_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetResponse) GetStatus() KVErrorCode {
	if x != nil {
		return x.Status
	}
	return KVErrorCode_STATUS_UNSPECIFIED
}

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_api_kvrpc_kv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_kvrpc_kv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_api_kvrpc_kv_proto_rawDescGZIP(), []int{4}
}

func (x *PutRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *PutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Status        KVErrorCode            `protobuf:"varint,2,opt,name=status,proto3,enum=kvrpc.KVErrorCode" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_api_kvrpc_kv_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_kvrpc_kv_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_api_kvrpc_kv_proto_rawDescGZIP(), []int{5}
}

func (x *PutResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PutResponse) GetStatus() KVErrorCode {
	if x != nil {
		return x.Status
	}
	return KVErrorCode_STATUS_UNSPECIFIED
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_api_kvrpc_kv_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_kvrpc_kv_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_kvrpc_kv_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        KVErrorCode            `protobuf:"varint,1,opt,name=status,proto3,enum=kvrpc.KVErrorCode" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_api_kvrpc_kv_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_kvrpc_kv_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_kvrpc_kv_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteResponse) GetStatus() KVErrorCode {
	if x != nil {
		return x.Status
	}
	return KVErrorCode_STATUS_UNSPECIFIED
}

type AppendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Suffix        []byte                 `protobuf:"bytes,2,opt,name=suffix,proto3" json:"suffix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendRequest) Reset() {
	*x = AppendRequest{}
	mi := &file_api_kvrpc_kv_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendRequest) ProtoMessage() {}

func (x *AppendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_kvrpc_kv_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendRequest.ProtoReflect.Descriptor instead.
func (*AppendRequest) Descriptor() ([]byte, []int) {
	return file_api_kvrpc_kv_proto_rawDescGZIP(), []int{8}
}

func (x *AppendRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *AppendRequest) GetSuffix() []byte {
	if x != nil {
		return x.Suffix
	}
	return nil
}

type AppendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Version       uint64                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Status        KVErrorCode            `protobuf:"varint,3,opt,name=status,proto3,enum=kvrpc.KVErrorCode" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendResponse) Reset() {
	*x = AppendResponse{}
	mi := &file_api_kvrpc_kv_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendResponse) ProtoMessage() {}

func (x *AppendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_kvrpc_kv_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendResponse.ProtoReflect.Descriptor instead.
func (*AppendResponse) Descriptor() ([]byte, []int) {
	return file_api_kvrpc_kv_proto_rawDescGZIP(), []int{9}
}

func (x *AppendResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *AppendResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *AppendResponse) GetStatus() KVErrorCode {
	if x != nil {
		return x.Status
	}
	return KVErrorCode_STATUS_UNSPECIFIED
}

type CASRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Key             []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ExpectedVersion uint64                 `protobuf:"varint,2,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	Value           []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CASRequest) Reset() {
	*x = CASRequest{}
	mi := &file_api_kvrpc_kv_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CASRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CASRequest) ProtoMessage() {}

func (x *CASRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_kvrpc_kv_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CASRequest.ProtoReflect.Descriptor instead.
func (*CASRequest) Descriptor() ([]byte, []int) {
	return file_api_kvrpc_kv_proto_rawDescGZIP(), []int{10}
}

func (x *CASRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *CASRequest) GetExpectedVersion() uint64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

func (x *CASRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type CASResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Status        KVErrorCode            `protobuf:"varint,2,opt,name=status,proto3,enum=kvrpc.KVErrorCode" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CASResponse) Reset() {
	*x = CASResponse{}
	mi := &file_api_kvrpc_kv_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CASResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CASResponse) ProtoMessage() {}

func (x *CASResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_kvrpc_kv_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CASResponse.ProtoReflect.Descriptor instead.
func (*CASResponse) Descriptor() ([]byte, []int) {
	return file_api_kvrpc_kv_proto_rawDescGZIP(), []int{11}
}

func (x *CASResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *CASResponse) GetStatus() KVErrorCode {
	if x != nil {
		return x.Status
	}
	return KVErrorCode_STATUS_UNSPECIFIED
}

type MultiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          [][]byte               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiRequest) Reset() {
	*x = MultiRequest{}
	mi := &file_api_kvrpc_kv_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiRequest) ProtoMessage() {}

func (x *MultiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_kvrpc_kv_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiRequest.ProtoReflect.Descriptor instead.
func (*MultiRequest) Descriptor() ([]byte, []int) {
	return file_api_kvrpc_kv_proto_rawDescGZIP(), []int{12}
}

func (x *MultiRequest) GetKeys() [][]byte {
	if x != nil {
		return x.Keys
	}
	return nil
}

// may use streaming rpc, now not included in service
type MultiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiResponse) Reset() {
	*x = MultiResponse{}
	mi := &file_api_kvrpc_kv_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiResponse) ProtoMessage() {}

func (x *MultiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_kvrpc_kv_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiResponse.ProtoReflect.Descriptor instead.
func (*MultiResponse) Descriptor() ([]byte, []int) {
	return file_api_kvrpc_kv_proto_rawDescGZIP(), []int{13}
}

var File_api_kvrpc_kv_proto protoreflect.FileDescriptor

const file_api_kvrpc_kv_proto_rawDesc = "" +
	"\n" +
	"\x12api/kvrpc/kv.proto\x12\x05kvrpc\"\xfa\x02\n" +
	"\x0fRequestWithMeta\x12\x1b\n" +
	"\tclient_ID\x18\x01 \x01(\tR\bclientID\x12\x1d\n" +
	"\n" +
	"request_ID\x18\x02 \x01(\x03R\trequestID\x124\n" +
	"\vget_request\x18\x03 \x01(\v2\x11.kvrpc.GetRequestH\x00R\n" +
	"getRequest\x124\n" +
	"\vput_request\x18\x04 \x01(\v2\x11.kvrpc.PutRequestH\x00R\n" +
	"putRequest\x12=\n" +
	"\x0edelete_request\x18\x05 \x01(\v2\x14.kvrpc.DeleteRequestH\x00R\rdeleteRequest\x12=\n" +
	"\x0eappend_request\x18\x06 \x01(\v2\x14.kvrpc.AppendRequestH\x00R\rappendRequest\x124\n" +
	"\vcas_request\x18\a \x01(\v2\x11.kvrpc.CASRequestH\x00R\n" +
	"casRequestB\v\n" +
	"\tKVRequest\"\xc7\x02\n" +
	"\bResponse\x127\n" +
	"\fget_response\x18\x01 \x01(\v2\x12.kvrpc.GetResponseH\x00R\vgetResponse\x127\n" +
	"\fput_response\x18\x02 \x01(\v2\x12.kvrpc.PutResponseH\x00R\vputResponse\x12@\n" +
	"\x0fdelete_response\x18\x03 \x01(\v2\x15.kvrpc.DeleteResponseH\x00R\x0edeleteResponse\x12@\n" +
	"\x0fappend_response\x18\x04 \x01(\v2\x15.kvrpc.AppendResponseH\x00R\x0eappendResponse\x127\n" +
	"\fcas_response\x18\x05 \x01(\v2\x12.kvrpc.CASResponseH\x00R\vcasResponseB\f\n" +
	"\n" +
	"KVResponse\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\"i\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\x12*\n" +
	"\x06status\x18\x03 \x01(\x0e2\x12.kvrpc.KVErrorCodeR\x06status\"4\n" +
	"\n" +
	"PutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"S\n" +
	"\vPutResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12*\n" +
	"\x06status\x18\x02 \x01(\x0e2\x12.kvrpc.KVErrorCodeR\x06status\"!\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\"<\n" +
	"\x0eDeleteResponse\x12*\n" +
	"\x06status\x18\x01 \x01(\x0e2\x12.kvrpc.KVErrorCodeR\x06status\"9\n" +
	"\rAppendRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x16\n" +
	"\x06suffix\x18\x02 \x01(\fR\x06suffix\"l\n" +
	"\x0eAppendResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\x12*\n" +
	"\x06status\x18\x03 \x01(\x0e2\x12.kvrpc.KVErrorCodeR\x06status\"_\n" +
	"\n" +
	"CASRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12)\n" +
	"\x10expected_version\x18\x02 \x01(\x04R\x0fexpectedVersion\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\"S\n" +
	"\vCASResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12*\n" +
	"\x06status\x18\x02 \x01(\x0e2\x12.kvrpc.KVErrorCodeR\x06status\"\"\n" +
	"\fMultiRequest\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\fR\x04keys\"\x0f\n" +
	"\rMultiResponse*\x8d\x01\n" +
	"\vKVErrorCode\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x06\n" +
	"\x02OK\x10\x01\x12\x11\n" +
	"\rKEY_NOT_FOUND\x10\x02\x12\x14\n" +
	"\x10VERSION_MISMATCH\x10\x03\x12\f\n" +
	"\bCONFLICT\x10\x04\x12\v\n" +
	"\aEXPIRED\x10\x05\x12\f\n" +
	"\bOUTDATED\x10\x06\x12\f\n" +
	"\bINTERNAL\x10\a2>\n" +
	"\bKeyValue\x122\n" +
	"\aExecute\x12\x16.kvrpc.RequestWithMeta\x1a\x0f.kvrpc.ResponseB3Z1github.com/DecarbonizedGlucose/rkv/api/kvrpc;kvpbb\x06proto3"

var (
	file_api_kvrpc_kv_proto_rawDescOnce sync.Once
	file_api_kvrpc_kv_proto_rawDescData []byte
)

func file_api_kvrpc_kv_proto_rawDescGZIP() []byte {
	file_api_kvrpc_kv_proto_rawDescOnce.Do(func() {
		file_api_kvrpc_kv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_kvrpc_kv_proto_rawDesc), len(file_api_kvrpc_kv_proto_rawDesc)))
	})
	return file_api_kvrpc_kv_proto_rawDescData
}

var file_api_kvrpc_kv_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_kvrpc_kv_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_kvrpc_kv_proto_goTypes = []any{
	(KVErrorCode)(0),        // 0: kvrpc.KVErrorCode
	(*RequestWithMeta)(nil), // 1: kvrpc.RequestWithMeta
	(*Response)(nil),        // 2: kvrpc.Response
	(*GetRequest)(nil),      // 3: kvrpc.GetRequest
	(*GetResponse)(nil),     // 4: kvrpc.GetResponse
	(*PutRequest)(nil),      // 5: kvrpc.PutRequest
	(*PutResponse)(nil),     // 6: kvrpc.PutResponse
	(*DeleteRequest)(nil),   // 7: kvrpc.DeleteRequest
	(*DeleteResponse)(nil),  // 8: kvrpc.DeleteResponse
	(*AppendRequest)(nil),   // 9: kvrpc.AppendRequest
	(*AppendResponse)(nil),  // 10: kvrpc.AppendResponse
	(*CASRequest)(nil),      // 11: kvrpc.CASRequest
	(*CASResponse)(nil),     // 12: kvrpc.CASResponse
	(*MultiRequest)(nil),    // 13: kvrpc.MultiRequest
	(*MultiResponse)(nil),   // 14: kvrpc.MultiResponse
}
var file_api_kvrpc_kv_proto_depIdxs = []int32{
	3,  // 0: kvrpc.RequestWithMeta.get_request:type_name -> kvrpc.GetRequest
	5,  // 1: kvrpc.RequestWithMeta.put_request:type_name -> kvrpc.PutRequest
	7,  // 2: kvrpc.RequestWithMeta.delete_request:type_name -> kvrpc.DeleteRequest
	9,  // 3: kvrpc.RequestWithMeta.append_request:type_name -> kvrpc.AppendRequest
	11, // 4: kvrpc.RequestWithMeta.cas_request:type_name -> kvrpc.CASRequest
	4,  // 5: kvrpc.Response.get_response:type_name -> kvrpc.GetResponse
	6,  // 6: kvrpc.Response.put_response:type_name -> kvrpc.PutResponse
	8,  // 7: kvrpc.Response.delete_response:type_name -> kvrpc.DeleteResponse
	10, // 8: kvrpc.Response.append_response:type_name -> kvrpc.AppendResponse
	12, // 9: kvrpc.Response.cas_response:type_name -> kvrpc.CASResponse
	0,  // 10: kvrpc.GetResponse.status:type_name -> kvrpc.KVErrorCode
	0,  // 11: kvrpc.PutResponse.status:type_name -> kvrpc.KVErrorCode
	0,  // 12: kvrpc.DeleteResponse.status:type_name -> kvrpc.KVErrorCode
	0,  // 13: kvrpc.AppendResponse.status:type_name -> kvrpc.KVErrorCode
	0,  // 14: kvrpc.CASResponse.status:type_name -> kvrpc.KVErrorCode
	1,  // 15: kvrpc.KeyValue.Execute:input_type -> kvrpc.RequestWithMeta
	2,  // 16: kvrpc.KeyValue.Execute:output_type -> kvrpc.Response
	16, // [16:17] is the sub-list for method output_type
	15, // [15:16] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_api_kvrpc_kv_proto_init() }
func file_api_kvrpc_kv_proto_init() {
	if File_api_kvrpc_kv_proto != nil {
		return
	}
	file_api_kvrpc_kv_proto_msgTypes[0].OneofWrappers = []any{
		(*RequestWithMeta_GetRequest)(nil),
		(*RequestWithMeta_PutRequest)(nil),
		(*RequestWithMeta_DeleteRequest)(nil),
		(*RequestWithMeta_AppendRequest)(nil),
		(*RequestWithMeta_CasRequest)(nil),
	}
	file_api_kvrpc_kv_proto_msgTypes[1].OneofWrappers = []any{
		(*Response_GetResponse)(nil),
		(*Response_PutResponse)(nil),
		(*Response_DeleteResponse)(nil),
		(*Response_AppendResponse)(nil),
		(*Response_CasResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_kvrpc_kv_proto_rawDesc), len(file_api_kvrpc_kv_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_kvrpc_kv_proto_goTypes,
		DependencyIndexes: file_api_kvrpc_kv_proto_depIdxs,
		EnumInfos:         file_api_kvrpc_kv_proto_enumTypes,
		MessageInfos:      file_api_kvrpc_kv_proto_msgTypes,
	}.Build()
	File_api_kvrpc_kv_proto = out.File
	file_api_kvrpc_kv_proto_goTypes = nil
	file_api_kvrpc_kv_proto_depIdxs = nil
}
