syntax = "proto3";

option go_package = "github.com/DecarbonizedGlucose/rkv/api/kvrpc;kvpb";

package kvrpc;

// Service

service KeyValue {
    rpc Execute(RequestWithMeta) returns (Response);
}

// Errors

enum KVErrorCode {
    STATUS_UNSPECIFIED = 0;

    OK                     = 1;     // No error
    KEY_NOT_FOUND          = 2;     // ErrNoKey
    VERSION_MISMATCH       = 3;     // ErrWrongVersion / ErrVersionMismatch
    CONFLICT               = 4;     // ErrConflict (transaction conflict, CAS failure, etc)
    EXPIRED                = 5;     // ErrExpired
    OUTDATED               = 6;     // ErrOutdated
    INTERNAL               = 7;     // Internal Error
}

// Requests and Responses

message RequestWithMeta {
    string client_ID = 1;
    int64 request_ID = 2;
    oneof KVRequest {
        GetRequest get_request = 3;
        PutRequest put_request = 4;
        DeleteRequest delete_request = 5;
        AppendRequest append_request = 6;
        CASRequest cas_request = 7;
    }
}

message Response {
    oneof KVResponse {
        GetResponse get_response = 1;
        PutResponse put_response = 2;
        DeleteResponse delete_response = 3;
        AppendResponse append_response = 4;
        CASResponse cas_response = 5;
    }
}

message GetRequest {
    bytes key = 1;
}

message GetResponse {
    bytes value = 1;
    uint64 version = 2;
    KVErrorCode status = 3;
}

message PutRequest {
    bytes key = 1;
    bytes value = 2;
}

message PutResponse {
    uint64 version = 1;
    KVErrorCode status = 2;
}

message DeleteRequest {
    bytes key = 1;
}

message DeleteResponse {
    KVErrorCode status = 1;
}

message AppendRequest {
    bytes key = 1;
    bytes suffix = 2;
}

message AppendResponse {
    bytes value = 1;
    uint64 version = 2;
    KVErrorCode status = 3;
}

message CASRequest {
    bytes key = 1;
    uint64 expected_version = 2;
    bytes value = 3;
}

message CASResponse {
    uint64 version = 1;
    KVErrorCode status = 2;
}


message MultiRequest {
    repeated bytes keys = 1;
}

// may use streaming rpc, now not included in service
message MultiResponse {

}

