// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: api/kvrpc/kv.proto

package kvpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusCode int32

const (
	StatusCode_STATUS_UNSPECIFIED StatusCode = 0
	StatusCode_OK                 StatusCode = 1  // No error
	StatusCode_KEY_NOT_FOUND      StatusCode = 2  // ErrNoKey
	StatusCode_VERSION_MISMATCH   StatusCode = 3  // ErrWrongVersion / ErrVersionMismatch
	StatusCode_CONFLICT           StatusCode = 4  // ErrConflict (transaction conflict, CAS failure, etc)
	StatusCode_COMPACTED          StatusCode = 5  // ErrCompacted
	StatusCode_EXPIRED            StatusCode = 6  // ErrExpired
	StatusCode_NOT_LEADER         StatusCode = 7  // ErrNotLeader / ErrWrongLeader
	StatusCode_TIMEOUT            StatusCode = 8  // ErrTimeout
	StatusCode_UNAVAILABLE        StatusCode = 9  // Service Unavailable
	StatusCode_INTERNAL           StatusCode = 10 // Internal Error
)

// Enum value maps for StatusCode.
var (
	StatusCode_name = map[int32]string{
		0:  "STATUS_UNSPECIFIED",
		1:  "OK",
		2:  "KEY_NOT_FOUND",
		3:  "VERSION_MISMATCH",
		4:  "CONFLICT",
		5:  "COMPACTED",
		6:  "EXPIRED",
		7:  "NOT_LEADER",
		8:  "TIMEOUT",
		9:  "UNAVAILABLE",
		10: "INTERNAL",
	}
	StatusCode_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"OK":                 1,
		"KEY_NOT_FOUND":      2,
		"VERSION_MISMATCH":   3,
		"CONFLICT":           4,
		"COMPACTED":          5,
		"EXPIRED":            6,
		"NOT_LEADER":         7,
		"TIMEOUT":            8,
		"UNAVAILABLE":        9,
		"INTERNAL":           10,
	}
)

func (x StatusCode) Enum() *StatusCode {
	p := new(StatusCode)
	*p = x
	return p
}

func (x StatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_kvrpc_kv_proto_enumTypes[0].Descriptor()
}

func (StatusCode) Type() protoreflect.EnumType {
	return &file_api_kvrpc_kv_proto_enumTypes[0]
}

func (x StatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusCode.Descriptor instead.
func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return file_api_kvrpc_kv_proto_rawDescGZIP(), []int{0}
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_api_kvrpc_kv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_kvrpc_kv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_api_kvrpc_kv_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Status        StatusCode             `protobuf:"varint,3,opt,name=status,proto3,enum=kvrpc.StatusCode" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_api_kvrpc_kv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_kvrpc_kv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_api_kvrpc_kv_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GetResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetResponse) GetStatus() StatusCode {
	if x != nil {
		return x.Status
	}
	return StatusCode_STATUS_UNSPECIFIED
}

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_api_kvrpc_kv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_kvrpc_kv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_api_kvrpc_kv_proto_rawDescGZIP(), []int{2}
}

func (x *PutRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Status        StatusCode             `protobuf:"varint,2,opt,name=status,proto3,enum=kvrpc.StatusCode" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_api_kvrpc_kv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_kvrpc_kv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_api_kvrpc_kv_proto_rawDescGZIP(), []int{3}
}

func (x *PutResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PutResponse) GetStatus() StatusCode {
	if x != nil {
		return x.Status
	}
	return StatusCode_STATUS_UNSPECIFIED
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_api_kvrpc_kv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_kvrpc_kv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_kvrpc_kv_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        StatusCode             `protobuf:"varint,1,opt,name=status,proto3,enum=kvrpc.StatusCode" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_api_kvrpc_kv_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_kvrpc_kv_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_kvrpc_kv_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteResponse) GetStatus() StatusCode {
	if x != nil {
		return x.Status
	}
	return StatusCode_STATUS_UNSPECIFIED
}

type AppendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Suffix        string                 `protobuf:"bytes,2,opt,name=suffix,proto3" json:"suffix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendRequest) Reset() {
	*x = AppendRequest{}
	mi := &file_api_kvrpc_kv_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendRequest) ProtoMessage() {}

func (x *AppendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_kvrpc_kv_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendRequest.ProtoReflect.Descriptor instead.
func (*AppendRequest) Descriptor() ([]byte, []int) {
	return file_api_kvrpc_kv_proto_rawDescGZIP(), []int{6}
}

func (x *AppendRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AppendRequest) GetSuffix() string {
	if x != nil {
		return x.Suffix
	}
	return ""
}

type AppendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Status        StatusCode             `protobuf:"varint,3,opt,name=status,proto3,enum=kvrpc.StatusCode" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendResponse) Reset() {
	*x = AppendResponse{}
	mi := &file_api_kvrpc_kv_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendResponse) ProtoMessage() {}

func (x *AppendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_kvrpc_kv_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendResponse.ProtoReflect.Descriptor instead.
func (*AppendResponse) Descriptor() ([]byte, []int) {
	return file_api_kvrpc_kv_proto_rawDescGZIP(), []int{7}
}

func (x *AppendResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *AppendResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *AppendResponse) GetStatus() StatusCode {
	if x != nil {
		return x.Status
	}
	return StatusCode_STATUS_UNSPECIFIED
}

type CASRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Key             string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ExpectedVersion int64                  `protobuf:"varint,2,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	Value           string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CASRequest) Reset() {
	*x = CASRequest{}
	mi := &file_api_kvrpc_kv_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CASRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CASRequest) ProtoMessage() {}

func (x *CASRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_kvrpc_kv_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CASRequest.ProtoReflect.Descriptor instead.
func (*CASRequest) Descriptor() ([]byte, []int) {
	return file_api_kvrpc_kv_proto_rawDescGZIP(), []int{8}
}

func (x *CASRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CASRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

func (x *CASRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type CASResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Status        StatusCode             `protobuf:"varint,2,opt,name=status,proto3,enum=kvrpc.StatusCode" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CASResponse) Reset() {
	*x = CASResponse{}
	mi := &file_api_kvrpc_kv_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CASResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CASResponse) ProtoMessage() {}

func (x *CASResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_kvrpc_kv_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CASResponse.ProtoReflect.Descriptor instead.
func (*CASResponse) Descriptor() ([]byte, []int) {
	return file_api_kvrpc_kv_proto_rawDescGZIP(), []int{9}
}

func (x *CASResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *CASResponse) GetStatus() StatusCode {
	if x != nil {
		return x.Status
	}
	return StatusCode_STATUS_UNSPECIFIED
}

type MultiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []string               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiRequest) Reset() {
	*x = MultiRequest{}
	mi := &file_api_kvrpc_kv_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiRequest) ProtoMessage() {}

func (x *MultiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_kvrpc_kv_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiRequest.ProtoReflect.Descriptor instead.
func (*MultiRequest) Descriptor() ([]byte, []int) {
	return file_api_kvrpc_kv_proto_rawDescGZIP(), []int{10}
}

func (x *MultiRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

// may use streaming rpc, now not included in service
type MultiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiResponse) Reset() {
	*x = MultiResponse{}
	mi := &file_api_kvrpc_kv_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiResponse) ProtoMessage() {}

func (x *MultiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_kvrpc_kv_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiResponse.ProtoReflect.Descriptor instead.
func (*MultiResponse) Descriptor() ([]byte, []int) {
	return file_api_kvrpc_kv_proto_rawDescGZIP(), []int{11}
}

var File_api_kvrpc_kv_proto protoreflect.FileDescriptor

const file_api_kvrpc_kv_proto_rawDesc = "" +
	"\n" +
	"\x12api/kvrpc/kv.proto\x12\x05kvrpc\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"h\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12)\n" +
	"\x06status\x18\x03 \x01(\x0e2\x11.kvrpc.StatusCodeR\x06status\"4\n" +
	"\n" +
	"PutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"R\n" +
	"\vPutResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x12)\n" +
	"\x06status\x18\x02 \x01(\x0e2\x11.kvrpc.StatusCodeR\x06status\"!\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\";\n" +
	"\x0eDeleteResponse\x12)\n" +
	"\x06status\x18\x01 \x01(\x0e2\x11.kvrpc.StatusCodeR\x06status\"9\n" +
	"\rAppendRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06suffix\x18\x02 \x01(\tR\x06suffix\"k\n" +
	"\x0eAppendResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12)\n" +
	"\x06status\x18\x03 \x01(\x0e2\x11.kvrpc.StatusCodeR\x06status\"_\n" +
	"\n" +
	"CASRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x10expected_version\x18\x02 \x01(\x03R\x0fexpectedVersion\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"R\n" +
	"\vCASResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x12)\n" +
	"\x06status\x18\x02 \x01(\x0e2\x11.kvrpc.StatusCodeR\x06status\"\"\n" +
	"\fMultiRequest\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\"\x0f\n" +
	"\rMultiResponse*\xbb\x01\n" +
	"\n" +
	"StatusCode\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x06\n" +
	"\x02OK\x10\x01\x12\x11\n" +
	"\rKEY_NOT_FOUND\x10\x02\x12\x14\n" +
	"\x10VERSION_MISMATCH\x10\x03\x12\f\n" +
	"\bCONFLICT\x10\x04\x12\r\n" +
	"\tCOMPACTED\x10\x05\x12\v\n" +
	"\aEXPIRED\x10\x06\x12\x0e\n" +
	"\n" +
	"NOT_LEADER\x10\a\x12\v\n" +
	"\aTIMEOUT\x10\b\x12\x0f\n" +
	"\vUNAVAILABLE\x10\t\x12\f\n" +
	"\bINTERNAL\x10\n" +
	"2\x82\x02\n" +
	"\bKeyValue\x12,\n" +
	"\x03Get\x12\x11.kvrpc.GetRequest\x1a\x12.kvrpc.GetResponse\x12,\n" +
	"\x03Put\x12\x11.kvrpc.PutRequest\x1a\x12.kvrpc.PutResponse\x125\n" +
	"\x06Delete\x12\x14.kvrpc.DeleteRequest\x1a\x15.kvrpc.DeleteResponse\x125\n" +
	"\x06Append\x12\x14.kvrpc.AppendRequest\x1a\x15.kvrpc.AppendResponse\x12,\n" +
	"\x03CAS\x12\x11.kvrpc.CASRequest\x1a\x12.kvrpc.CASResponseB3Z1github.com/DecarbonizedGlucose/rkv/api/kvrpc/kvpbb\x06proto3"

var (
	file_api_kvrpc_kv_proto_rawDescOnce sync.Once
	file_api_kvrpc_kv_proto_rawDescData []byte
)

func file_api_kvrpc_kv_proto_rawDescGZIP() []byte {
	file_api_kvrpc_kv_proto_rawDescOnce.Do(func() {
		file_api_kvrpc_kv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_kvrpc_kv_proto_rawDesc), len(file_api_kvrpc_kv_proto_rawDesc)))
	})
	return file_api_kvrpc_kv_proto_rawDescData
}

var file_api_kvrpc_kv_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_kvrpc_kv_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_kvrpc_kv_proto_goTypes = []any{
	(StatusCode)(0),        // 0: kvrpc.StatusCode
	(*GetRequest)(nil),     // 1: kvrpc.GetRequest
	(*GetResponse)(nil),    // 2: kvrpc.GetResponse
	(*PutRequest)(nil),     // 3: kvrpc.PutRequest
	(*PutResponse)(nil),    // 4: kvrpc.PutResponse
	(*DeleteRequest)(nil),  // 5: kvrpc.DeleteRequest
	(*DeleteResponse)(nil), // 6: kvrpc.DeleteResponse
	(*AppendRequest)(nil),  // 7: kvrpc.AppendRequest
	(*AppendResponse)(nil), // 8: kvrpc.AppendResponse
	(*CASRequest)(nil),     // 9: kvrpc.CASRequest
	(*CASResponse)(nil),    // 10: kvrpc.CASResponse
	(*MultiRequest)(nil),   // 11: kvrpc.MultiRequest
	(*MultiResponse)(nil),  // 12: kvrpc.MultiResponse
}
var file_api_kvrpc_kv_proto_depIdxs = []int32{
	0,  // 0: kvrpc.GetResponse.status:type_name -> kvrpc.StatusCode
	0,  // 1: kvrpc.PutResponse.status:type_name -> kvrpc.StatusCode
	0,  // 2: kvrpc.DeleteResponse.status:type_name -> kvrpc.StatusCode
	0,  // 3: kvrpc.AppendResponse.status:type_name -> kvrpc.StatusCode
	0,  // 4: kvrpc.CASResponse.status:type_name -> kvrpc.StatusCode
	1,  // 5: kvrpc.KeyValue.Get:input_type -> kvrpc.GetRequest
	3,  // 6: kvrpc.KeyValue.Put:input_type -> kvrpc.PutRequest
	5,  // 7: kvrpc.KeyValue.Delete:input_type -> kvrpc.DeleteRequest
	7,  // 8: kvrpc.KeyValue.Append:input_type -> kvrpc.AppendRequest
	9,  // 9: kvrpc.KeyValue.CAS:input_type -> kvrpc.CASRequest
	2,  // 10: kvrpc.KeyValue.Get:output_type -> kvrpc.GetResponse
	4,  // 11: kvrpc.KeyValue.Put:output_type -> kvrpc.PutResponse
	6,  // 12: kvrpc.KeyValue.Delete:output_type -> kvrpc.DeleteResponse
	8,  // 13: kvrpc.KeyValue.Append:output_type -> kvrpc.AppendResponse
	10, // 14: kvrpc.KeyValue.CAS:output_type -> kvrpc.CASResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_kvrpc_kv_proto_init() }
func file_api_kvrpc_kv_proto_init() {
	if File_api_kvrpc_kv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_kvrpc_kv_proto_rawDesc), len(file_api_kvrpc_kv_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_kvrpc_kv_proto_goTypes,
		DependencyIndexes: file_api_kvrpc_kv_proto_depIdxs,
		EnumInfos:         file_api_kvrpc_kv_proto_enumTypes,
		MessageInfos:      file_api_kvrpc_kv_proto_msgTypes,
	}.Build()
	File_api_kvrpc_kv_proto = out.File
	file_api_kvrpc_kv_proto_goTypes = nil
	file_api_kvrpc_kv_proto_depIdxs = nil
}
