// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: api/raftapplier/raftapplier.proto

package raftapplierpb

import (
	kvrpc "github.com/DecarbonizedGlucose/rkv/api/kvrpc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestWithMeta struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Client_ID  string                 `protobuf:"bytes,1,opt,name=client_ID,json=clientID,proto3" json:"client_ID,omitempty"`
	Request_ID string                 `protobuf:"bytes,2,opt,name=request_ID,json=requestID,proto3" json:"request_ID,omitempty"`
	// Types that are valid to be assigned to KVRequest:
	//
	//	*RequestWithMeta_GetRequest
	//	*RequestWithMeta_PutRequest
	//	*RequestWithMeta_DeleteRequest
	//	*RequestWithMeta_AppendRequest
	//	*RequestWithMeta_CasRequest
	KVRequest     isRequestWithMeta_KVRequest `protobuf_oneof:"KVRequest"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestWithMeta) Reset() {
	*x = RequestWithMeta{}
	mi := &file_api_raftapplier_raftapplier_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestWithMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestWithMeta) ProtoMessage() {}

func (x *RequestWithMeta) ProtoReflect() protoreflect.Message {
	mi := &file_api_raftapplier_raftapplier_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestWithMeta.ProtoReflect.Descriptor instead.
func (*RequestWithMeta) Descriptor() ([]byte, []int) {
	return file_api_raftapplier_raftapplier_proto_rawDescGZIP(), []int{0}
}

func (x *RequestWithMeta) GetClient_ID() string {
	if x != nil {
		return x.Client_ID
	}
	return ""
}

func (x *RequestWithMeta) GetRequest_ID() string {
	if x != nil {
		return x.Request_ID
	}
	return ""
}

func (x *RequestWithMeta) GetKVRequest() isRequestWithMeta_KVRequest {
	if x != nil {
		return x.KVRequest
	}
	return nil
}

func (x *RequestWithMeta) GetGetRequest() *kvrpc.GetRequest {
	if x != nil {
		if x, ok := x.KVRequest.(*RequestWithMeta_GetRequest); ok {
			return x.GetRequest
		}
	}
	return nil
}

func (x *RequestWithMeta) GetPutRequest() *kvrpc.PutRequest {
	if x != nil {
		if x, ok := x.KVRequest.(*RequestWithMeta_PutRequest); ok {
			return x.PutRequest
		}
	}
	return nil
}

func (x *RequestWithMeta) GetDeleteRequest() *kvrpc.DeleteRequest {
	if x != nil {
		if x, ok := x.KVRequest.(*RequestWithMeta_DeleteRequest); ok {
			return x.DeleteRequest
		}
	}
	return nil
}

func (x *RequestWithMeta) GetAppendRequest() *kvrpc.AppendRequest {
	if x != nil {
		if x, ok := x.KVRequest.(*RequestWithMeta_AppendRequest); ok {
			return x.AppendRequest
		}
	}
	return nil
}

func (x *RequestWithMeta) GetCasRequest() *kvrpc.CASRequest {
	if x != nil {
		if x, ok := x.KVRequest.(*RequestWithMeta_CasRequest); ok {
			return x.CasRequest
		}
	}
	return nil
}

type isRequestWithMeta_KVRequest interface {
	isRequestWithMeta_KVRequest()
}

type RequestWithMeta_GetRequest struct {
	GetRequest *kvrpc.GetRequest `protobuf:"bytes,3,opt,name=get_request,json=getRequest,proto3,oneof"`
}

type RequestWithMeta_PutRequest struct {
	PutRequest *kvrpc.PutRequest `protobuf:"bytes,4,opt,name=put_request,json=putRequest,proto3,oneof"`
}

type RequestWithMeta_DeleteRequest struct {
	DeleteRequest *kvrpc.DeleteRequest `protobuf:"bytes,5,opt,name=delete_request,json=deleteRequest,proto3,oneof"`
}

type RequestWithMeta_AppendRequest struct {
	AppendRequest *kvrpc.AppendRequest `protobuf:"bytes,6,opt,name=append_request,json=appendRequest,proto3,oneof"`
}

type RequestWithMeta_CasRequest struct {
	CasRequest *kvrpc.CASRequest `protobuf:"bytes,7,opt,name=cas_request,json=casRequest,proto3,oneof"` // and, the multi-get request, TODO
}

func (*RequestWithMeta_GetRequest) isRequestWithMeta_KVRequest() {}

func (*RequestWithMeta_PutRequest) isRequestWithMeta_KVRequest() {}

func (*RequestWithMeta_DeleteRequest) isRequestWithMeta_KVRequest() {}

func (*RequestWithMeta_AppendRequest) isRequestWithMeta_KVRequest() {}

func (*RequestWithMeta_CasRequest) isRequestWithMeta_KVRequest() {}

type Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to KVResponse:
	//
	//	*Response_GetResponse
	//	*Response_PutResponse
	//	*Response_DeleteResponse
	//	*Response_AppendResponse
	//	*Response_CasResponse
	KVResponse    isResponse_KVResponse `protobuf_oneof:"KVResponse"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_api_raftapplier_raftapplier_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_raftapplier_raftapplier_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_api_raftapplier_raftapplier_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetKVResponse() isResponse_KVResponse {
	if x != nil {
		return x.KVResponse
	}
	return nil
}

func (x *Response) GetGetResponse() *kvrpc.GetResponse {
	if x != nil {
		if x, ok := x.KVResponse.(*Response_GetResponse); ok {
			return x.GetResponse
		}
	}
	return nil
}

func (x *Response) GetPutResponse() *kvrpc.PutResponse {
	if x != nil {
		if x, ok := x.KVResponse.(*Response_PutResponse); ok {
			return x.PutResponse
		}
	}
	return nil
}

func (x *Response) GetDeleteResponse() *kvrpc.DeleteResponse {
	if x != nil {
		if x, ok := x.KVResponse.(*Response_DeleteResponse); ok {
			return x.DeleteResponse
		}
	}
	return nil
}

func (x *Response) GetAppendResponse() *kvrpc.AppendResponse {
	if x != nil {
		if x, ok := x.KVResponse.(*Response_AppendResponse); ok {
			return x.AppendResponse
		}
	}
	return nil
}

func (x *Response) GetCasResponse() *kvrpc.CASResponse {
	if x != nil {
		if x, ok := x.KVResponse.(*Response_CasResponse); ok {
			return x.CasResponse
		}
	}
	return nil
}

type isResponse_KVResponse interface {
	isResponse_KVResponse()
}

type Response_GetResponse struct {
	GetResponse *kvrpc.GetResponse `protobuf:"bytes,1,opt,name=get_response,json=getResponse,proto3,oneof"`
}

type Response_PutResponse struct {
	PutResponse *kvrpc.PutResponse `protobuf:"bytes,2,opt,name=put_response,json=putResponse,proto3,oneof"`
}

type Response_DeleteResponse struct {
	DeleteResponse *kvrpc.DeleteResponse `protobuf:"bytes,3,opt,name=delete_response,json=deleteResponse,proto3,oneof"`
}

type Response_AppendResponse struct {
	AppendResponse *kvrpc.AppendResponse `protobuf:"bytes,4,opt,name=append_response,json=appendResponse,proto3,oneof"`
}

type Response_CasResponse struct {
	CasResponse *kvrpc.CASResponse `protobuf:"bytes,5,opt,name=cas_response,json=casResponse,proto3,oneof"` // and, the multi-get response, TODO
}

func (*Response_GetResponse) isResponse_KVResponse() {}

func (*Response_PutResponse) isResponse_KVResponse() {}

func (*Response_DeleteResponse) isResponse_KVResponse() {}

func (*Response_AppendResponse) isResponse_KVResponse() {}

func (*Response_CasResponse) isResponse_KVResponse() {}

var File_api_raftapplier_raftapplier_proto protoreflect.FileDescriptor

const file_api_raftapplier_raftapplier_proto_rawDesc = "" +
	"\n" +
	"!api/raftapplier/raftapplier.proto\x12\vraftapplier\x1a\x12api/kvrpc/kv.proto\"\xfa\x02\n" +
	"\x0fRequestWithMeta\x12\x1b\n" +
	"\tclient_ID\x18\x01 \x01(\tR\bclientID\x12\x1d\n" +
	"\n" +
	"request_ID\x18\x02 \x01(\tR\trequestID\x124\n" +
	"\vget_request\x18\x03 \x01(\v2\x11.kvrpc.GetRequestH\x00R\n" +
	"getRequest\x124\n" +
	"\vput_request\x18\x04 \x01(\v2\x11.kvrpc.PutRequestH\x00R\n" +
	"putRequest\x12=\n" +
	"\x0edelete_request\x18\x05 \x01(\v2\x14.kvrpc.DeleteRequestH\x00R\rdeleteRequest\x12=\n" +
	"\x0eappend_request\x18\x06 \x01(\v2\x14.kvrpc.AppendRequestH\x00R\rappendRequest\x124\n" +
	"\vcas_request\x18\a \x01(\v2\x11.kvrpc.CASRequestH\x00R\n" +
	"casRequestB\v\n" +
	"\tKVRequest\"\xc7\x02\n" +
	"\bResponse\x127\n" +
	"\fget_response\x18\x01 \x01(\v2\x12.kvrpc.GetResponseH\x00R\vgetResponse\x127\n" +
	"\fput_response\x18\x02 \x01(\v2\x12.kvrpc.PutResponseH\x00R\vputResponse\x12@\n" +
	"\x0fdelete_response\x18\x03 \x01(\v2\x15.kvrpc.DeleteResponseH\x00R\x0edeleteResponse\x12@\n" +
	"\x0fappend_response\x18\x04 \x01(\v2\x15.kvrpc.AppendResponseH\x00R\x0eappendResponse\x127\n" +
	"\fcas_response\x18\x05 \x01(\v2\x12.kvrpc.CASResponseH\x00R\vcasResponseB\f\n" +
	"\n" +
	"KVResponseBBZ@github.com/DecarbonizedGlucose/rkv/api/raftapplier;raftapplierpbb\x06proto3"

var (
	file_api_raftapplier_raftapplier_proto_rawDescOnce sync.Once
	file_api_raftapplier_raftapplier_proto_rawDescData []byte
)

func file_api_raftapplier_raftapplier_proto_rawDescGZIP() []byte {
	file_api_raftapplier_raftapplier_proto_rawDescOnce.Do(func() {
		file_api_raftapplier_raftapplier_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_raftapplier_raftapplier_proto_rawDesc), len(file_api_raftapplier_raftapplier_proto_rawDesc)))
	})
	return file_api_raftapplier_raftapplier_proto_rawDescData
}

var file_api_raftapplier_raftapplier_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_raftapplier_raftapplier_proto_goTypes = []any{
	(*RequestWithMeta)(nil),      // 0: raftapplier.RequestWithMeta
	(*Response)(nil),             // 1: raftapplier.Response
	(*kvrpc.GetRequest)(nil),     // 2: kvrpc.GetRequest
	(*kvrpc.PutRequest)(nil),     // 3: kvrpc.PutRequest
	(*kvrpc.DeleteRequest)(nil),  // 4: kvrpc.DeleteRequest
	(*kvrpc.AppendRequest)(nil),  // 5: kvrpc.AppendRequest
	(*kvrpc.CASRequest)(nil),     // 6: kvrpc.CASRequest
	(*kvrpc.GetResponse)(nil),    // 7: kvrpc.GetResponse
	(*kvrpc.PutResponse)(nil),    // 8: kvrpc.PutResponse
	(*kvrpc.DeleteResponse)(nil), // 9: kvrpc.DeleteResponse
	(*kvrpc.AppendResponse)(nil), // 10: kvrpc.AppendResponse
	(*kvrpc.CASResponse)(nil),    // 11: kvrpc.CASResponse
}
var file_api_raftapplier_raftapplier_proto_depIdxs = []int32{
	2,  // 0: raftapplier.RequestWithMeta.get_request:type_name -> kvrpc.GetRequest
	3,  // 1: raftapplier.RequestWithMeta.put_request:type_name -> kvrpc.PutRequest
	4,  // 2: raftapplier.RequestWithMeta.delete_request:type_name -> kvrpc.DeleteRequest
	5,  // 3: raftapplier.RequestWithMeta.append_request:type_name -> kvrpc.AppendRequest
	6,  // 4: raftapplier.RequestWithMeta.cas_request:type_name -> kvrpc.CASRequest
	7,  // 5: raftapplier.Response.get_response:type_name -> kvrpc.GetResponse
	8,  // 6: raftapplier.Response.put_response:type_name -> kvrpc.PutResponse
	9,  // 7: raftapplier.Response.delete_response:type_name -> kvrpc.DeleteResponse
	10, // 8: raftapplier.Response.append_response:type_name -> kvrpc.AppendResponse
	11, // 9: raftapplier.Response.cas_response:type_name -> kvrpc.CASResponse
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_api_raftapplier_raftapplier_proto_init() }
func file_api_raftapplier_raftapplier_proto_init() {
	if File_api_raftapplier_raftapplier_proto != nil {
		return
	}
	file_api_raftapplier_raftapplier_proto_msgTypes[0].OneofWrappers = []any{
		(*RequestWithMeta_GetRequest)(nil),
		(*RequestWithMeta_PutRequest)(nil),
		(*RequestWithMeta_DeleteRequest)(nil),
		(*RequestWithMeta_AppendRequest)(nil),
		(*RequestWithMeta_CasRequest)(nil),
	}
	file_api_raftapplier_raftapplier_proto_msgTypes[1].OneofWrappers = []any{
		(*Response_GetResponse)(nil),
		(*Response_PutResponse)(nil),
		(*Response_DeleteResponse)(nil),
		(*Response_AppendResponse)(nil),
		(*Response_CasResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_raftapplier_raftapplier_proto_rawDesc), len(file_api_raftapplier_raftapplier_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_raftapplier_raftapplier_proto_goTypes,
		DependencyIndexes: file_api_raftapplier_raftapplier_proto_depIdxs,
		MessageInfos:      file_api_raftapplier_raftapplier_proto_msgTypes,
	}.Build()
	File_api_raftapplier_raftapplier_proto = out.File
	file_api_raftapplier_raftapplier_proto_goTypes = nil
	file_api_raftapplier_raftapplier_proto_depIdxs = nil
}
