// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: internal/raft/proto/persist.proto

package persistpb

import (
	raftrpc "github.com/DecarbonizedGlucose/rkv/api/raftrpc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PersistState struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CurrentTerm       int64                  `protobuf:"varint,1,opt,name=current_term,json=currentTerm,proto3" json:"current_term,omitempty"`
	VotedFor          int64                  `protobuf:"varint,2,opt,name=voted_for,json=votedFor,proto3" json:"voted_for,omitempty"`
	LastIncludedIndex int64                  `protobuf:"varint,3,opt,name=last_included_index,json=lastIncludedIndex,proto3" json:"last_included_index,omitempty"`
	LastIncludedTerm  int64                  `protobuf:"varint,4,opt,name=last_included_term,json=lastIncludedTerm,proto3" json:"last_included_term,omitempty"`
	Log               []*raftrpc.LogEntry    `protobuf:"bytes,5,rep,name=log,proto3" json:"log,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PersistState) Reset() {
	*x = PersistState{}
	mi := &file_internal_raft_proto_persist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersistState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersistState) ProtoMessage() {}

func (x *PersistState) ProtoReflect() protoreflect.Message {
	mi := &file_internal_raft_proto_persist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersistState.ProtoReflect.Descriptor instead.
func (*PersistState) Descriptor() ([]byte, []int) {
	return file_internal_raft_proto_persist_proto_rawDescGZIP(), []int{0}
}

func (x *PersistState) GetCurrentTerm() int64 {
	if x != nil {
		return x.CurrentTerm
	}
	return 0
}

func (x *PersistState) GetVotedFor() int64 {
	if x != nil {
		return x.VotedFor
	}
	return 0
}

func (x *PersistState) GetLastIncludedIndex() int64 {
	if x != nil {
		return x.LastIncludedIndex
	}
	return 0
}

func (x *PersistState) GetLastIncludedTerm() int64 {
	if x != nil {
		return x.LastIncludedTerm
	}
	return 0
}

func (x *PersistState) GetLog() []*raftrpc.LogEntry {
	if x != nil {
		return x.Log
	}
	return nil
}

var File_internal_raft_proto_persist_proto protoreflect.FileDescriptor

const file_internal_raft_proto_persist_proto_rawDesc = "" +
	"\n" +
	"!internal/raft/proto/persist.proto\x12\apersist\x1a\x1bapi/raftrpc/consensus.proto\"\xd1\x01\n" +
	"\fPersistState\x12!\n" +
	"\fcurrent_term\x18\x01 \x01(\x03R\vcurrentTerm\x12\x1b\n" +
	"\tvoted_for\x18\x02 \x01(\x03R\bvotedFor\x12.\n" +
	"\x13last_included_index\x18\x03 \x01(\x03R\x11lastIncludedIndex\x12,\n" +
	"\x12last_included_term\x18\x04 \x01(\x03R\x10lastIncludedTerm\x12#\n" +
	"\x03log\x18\x05 \x03(\v2\x11.raftrpc.LogEntryR\x03logBBZ@github.com/DecarbonizedGlucose/rkv/internal/raft/proto;persistpbb\x06proto3"

var (
	file_internal_raft_proto_persist_proto_rawDescOnce sync.Once
	file_internal_raft_proto_persist_proto_rawDescData []byte
)

func file_internal_raft_proto_persist_proto_rawDescGZIP() []byte {
	file_internal_raft_proto_persist_proto_rawDescOnce.Do(func() {
		file_internal_raft_proto_persist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_raft_proto_persist_proto_rawDesc), len(file_internal_raft_proto_persist_proto_rawDesc)))
	})
	return file_internal_raft_proto_persist_proto_rawDescData
}

var file_internal_raft_proto_persist_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_raft_proto_persist_proto_goTypes = []any{
	(*PersistState)(nil),     // 0: persist.PersistState
	(*raftrpc.LogEntry)(nil), // 1: raftrpc.LogEntry
}
var file_internal_raft_proto_persist_proto_depIdxs = []int32{
	1, // 0: persist.PersistState.log:type_name -> raftrpc.LogEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_raft_proto_persist_proto_init() }
func file_internal_raft_proto_persist_proto_init() {
	if File_internal_raft_proto_persist_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_raft_proto_persist_proto_rawDesc), len(file_internal_raft_proto_persist_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_raft_proto_persist_proto_goTypes,
		DependencyIndexes: file_internal_raft_proto_persist_proto_depIdxs,
		MessageInfos:      file_internal_raft_proto_persist_proto_msgTypes,
	}.Build()
	File_internal_raft_proto_persist_proto = out.File
	file_internal_raft_proto_persist_proto_goTypes = nil
	file_internal_raft_proto_persist_proto_depIdxs = nil
}
