// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: raft.proto

package raftpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_MESSAGE_TYPE_UNSPECIFIED           MessageType = 0
	MessageType_MESSAGE_TYPE_APPEND_REQ            MessageType = 1
	MessageType_MESSAGE_TYPE_APPEND_RESP           MessageType = 2
	MessageType_MESSAGE_TYPE_REQUEST_VOTE_REQ      MessageType = 3
	MessageType_MESSAGE_TYPE_REQUEST_VOTE_RESP     MessageType = 4
	MessageType_MESSAGE_TYPE_INSTALL_SNAPSHOT_REQ  MessageType = 5
	MessageType_MESSAGE_TYPE_INSTALL_SNAPSHOT_RESP MessageType = 6
	MessageType_MESSAGE_TYPE_HEARTBEAT             MessageType = 7
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "MESSAGE_TYPE_UNSPECIFIED",
		1: "MESSAGE_TYPE_APPEND_REQ",
		2: "MESSAGE_TYPE_APPEND_RESP",
		3: "MESSAGE_TYPE_REQUEST_VOTE_REQ",
		4: "MESSAGE_TYPE_REQUEST_VOTE_RESP",
		5: "MESSAGE_TYPE_INSTALL_SNAPSHOT_REQ",
		6: "MESSAGE_TYPE_INSTALL_SNAPSHOT_RESP",
		7: "MESSAGE_TYPE_HEARTBEAT",
	}
	MessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNSPECIFIED":           0,
		"MESSAGE_TYPE_APPEND_REQ":            1,
		"MESSAGE_TYPE_APPEND_RESP":           2,
		"MESSAGE_TYPE_REQUEST_VOTE_REQ":      3,
		"MESSAGE_TYPE_REQUEST_VOTE_RESP":     4,
		"MESSAGE_TYPE_INSTALL_SNAPSHOT_REQ":  5,
		"MESSAGE_TYPE_INSTALL_SNAPSHOT_RESP": 6,
		"MESSAGE_TYPE_HEARTBEAT":             7,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_raft_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_raft_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{0}
}

type Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`   // 任期号
	Index         uint64                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"` // 日志索引
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`    // 序列化的 command
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_raft_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{0}
}

func (x *Entry) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *Entry) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Entry) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type RaftMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=raftpb.MessageType" json:"type,omitempty"`
	From  uint64                 `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"` // 发送者节点 ID
	To    uint64                 `protobuf:"varint,3,opt,name=to,proto3" json:"to,omitempty"`     // 接收者节点 ID
	Term  uint64                 `protobuf:"varint,4,opt,name=term,proto3" json:"term,omitempty"` // 发送者任期
	// Types that are valid to be assigned to Body:
	//
	//	*RaftMessage_AppendReq
	//	*RaftMessage_AppendResp
	//	*RaftMessage_VoteReq
	//	*RaftMessage_VoteResp
	//	*RaftMessage_SnapReq
	//	*RaftMessage_SnapResp
	//	*RaftMessage_Heartbeat
	Body          isRaftMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaftMessage) Reset() {
	*x = RaftMessage{}
	mi := &file_raft_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftMessage) ProtoMessage() {}

func (x *RaftMessage) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftMessage.ProtoReflect.Descriptor instead.
func (*RaftMessage) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{1}
}

func (x *RaftMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNSPECIFIED
}

func (x *RaftMessage) GetFrom() uint64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *RaftMessage) GetTo() uint64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *RaftMessage) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RaftMessage) GetBody() isRaftMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *RaftMessage) GetAppendReq() *AppendEntriesRequest {
	if x != nil {
		if x, ok := x.Body.(*RaftMessage_AppendReq); ok {
			return x.AppendReq
		}
	}
	return nil
}

func (x *RaftMessage) GetAppendResp() *AppendEntriesResponse {
	if x != nil {
		if x, ok := x.Body.(*RaftMessage_AppendResp); ok {
			return x.AppendResp
		}
	}
	return nil
}

func (x *RaftMessage) GetVoteReq() *RequestVoteRequest {
	if x != nil {
		if x, ok := x.Body.(*RaftMessage_VoteReq); ok {
			return x.VoteReq
		}
	}
	return nil
}

func (x *RaftMessage) GetVoteResp() *RequestVoteResponse {
	if x != nil {
		if x, ok := x.Body.(*RaftMessage_VoteResp); ok {
			return x.VoteResp
		}
	}
	return nil
}

func (x *RaftMessage) GetSnapReq() *InstallSnapshotRequest {
	if x != nil {
		if x, ok := x.Body.(*RaftMessage_SnapReq); ok {
			return x.SnapReq
		}
	}
	return nil
}

func (x *RaftMessage) GetSnapResp() *InstallSnapshotResponse {
	if x != nil {
		if x, ok := x.Body.(*RaftMessage_SnapResp); ok {
			return x.SnapResp
		}
	}
	return nil
}

func (x *RaftMessage) GetHeartbeat() *HeartbeatNotify {
	if x != nil {
		if x, ok := x.Body.(*RaftMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isRaftMessage_Body interface {
	isRaftMessage_Body()
}

type RaftMessage_AppendReq struct {
	AppendReq *AppendEntriesRequest `protobuf:"bytes,10,opt,name=append_req,json=appendReq,proto3,oneof"`
}

type RaftMessage_AppendResp struct {
	AppendResp *AppendEntriesResponse `protobuf:"bytes,11,opt,name=append_resp,json=appendResp,proto3,oneof"`
}

type RaftMessage_VoteReq struct {
	VoteReq *RequestVoteRequest `protobuf:"bytes,12,opt,name=vote_req,json=voteReq,proto3,oneof"`
}

type RaftMessage_VoteResp struct {
	VoteResp *RequestVoteResponse `protobuf:"bytes,13,opt,name=vote_resp,json=voteResp,proto3,oneof"`
}

type RaftMessage_SnapReq struct {
	SnapReq *InstallSnapshotRequest `protobuf:"bytes,14,opt,name=snap_req,json=snapReq,proto3,oneof"`
}

type RaftMessage_SnapResp struct {
	SnapResp *InstallSnapshotResponse `protobuf:"bytes,15,opt,name=snap_resp,json=snapResp,proto3,oneof"`
}

type RaftMessage_Heartbeat struct {
	Heartbeat *HeartbeatNotify `protobuf:"bytes,16,opt,name=heartbeat,proto3,oneof"`
}

func (*RaftMessage_AppendReq) isRaftMessage_Body() {}

func (*RaftMessage_AppendResp) isRaftMessage_Body() {}

func (*RaftMessage_VoteReq) isRaftMessage_Body() {}

func (*RaftMessage_VoteResp) isRaftMessage_Body() {}

func (*RaftMessage_SnapReq) isRaftMessage_Body() {}

func (*RaftMessage_SnapResp) isRaftMessage_Body() {}

func (*RaftMessage_Heartbeat) isRaftMessage_Body() {}

type AppendEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId      uint64                 `protobuf:"varint,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	PrevLogIndex  uint64                 `protobuf:"varint,3,opt,name=prev_log_index,json=prevLogIndex,proto3" json:"prev_log_index,omitempty"`
	PrevLogTerm   uint64                 `protobuf:"varint,4,opt,name=prev_log_term,json=prevLogTerm,proto3" json:"prev_log_term,omitempty"`
	Entries       []*Entry               `protobuf:"bytes,5,rep,name=entries,proto3" json:"entries,omitempty"`
	LeaderCommit  uint64                 `protobuf:"varint,6,opt,name=leader_commit,json=leaderCommit,proto3" json:"leader_commit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntriesRequest) Reset() {
	*x = AppendEntriesRequest{}
	mi := &file_raft_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesRequest) ProtoMessage() {}

func (x *AppendEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesRequest.ProtoReflect.Descriptor instead.
func (*AppendEntriesRequest) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{2}
}

func (x *AppendEntriesRequest) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendEntriesRequest) GetLeaderId() uint64 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *AppendEntriesRequest) GetPrevLogIndex() uint64 {
	if x != nil {
		return x.PrevLogIndex
	}
	return 0
}

func (x *AppendEntriesRequest) GetPrevLogTerm() uint64 {
	if x != nil {
		return x.PrevLogTerm
	}
	return 0
}

func (x *AppendEntriesRequest) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *AppendEntriesRequest) GetLeaderCommit() uint64 {
	if x != nil {
		return x.LeaderCommit
	}
	return 0
}

type AppendEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	LastLog       uint64                 `protobuf:"varint,2,opt,name=last_log,json=lastLog,proto3" json:"last_log,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	RejectHint    uint64                 `protobuf:"varint,4,opt,name=reject_hint,json=rejectHint,proto3" json:"reject_hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntriesResponse) Reset() {
	*x = AppendEntriesResponse{}
	mi := &file_raft_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesResponse) ProtoMessage() {}

func (x *AppendEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesResponse.ProtoReflect.Descriptor instead.
func (*AppendEntriesResponse) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{3}
}

func (x *AppendEntriesResponse) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendEntriesResponse) GetLastLog() uint64 {
	if x != nil {
		return x.LastLog
	}
	return 0
}

func (x *AppendEntriesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AppendEntriesResponse) GetRejectHint() uint64 {
	if x != nil {
		return x.RejectHint
	}
	return 0
}

type RequestVoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	CandidateId   uint64                 `protobuf:"varint,2,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	LastLogIndex  uint64                 `protobuf:"varint,3,opt,name=last_log_index,json=lastLogIndex,proto3" json:"last_log_index,omitempty"`
	LastLogTerm   uint64                 `protobuf:"varint,4,opt,name=last_log_term,json=lastLogTerm,proto3" json:"last_log_term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteRequest) Reset() {
	*x = RequestVoteRequest{}
	mi := &file_raft_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteRequest) ProtoMessage() {}

func (x *RequestVoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteRequest.ProtoReflect.Descriptor instead.
func (*RequestVoteRequest) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{4}
}

func (x *RequestVoteRequest) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RequestVoteRequest) GetCandidateId() uint64 {
	if x != nil {
		return x.CandidateId
	}
	return 0
}

func (x *RequestVoteRequest) GetLastLogIndex() uint64 {
	if x != nil {
		return x.LastLogIndex
	}
	return 0
}

func (x *RequestVoteRequest) GetLastLogTerm() uint64 {
	if x != nil {
		return x.LastLogTerm
	}
	return 0
}

type RequestVoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	VoteGranted   bool                   `protobuf:"varint,2,opt,name=vote_granted,json=voteGranted,proto3" json:"vote_granted,omitempty"`
	VoterId       uint64                 `protobuf:"varint,3,opt,name=voter_id,json=voterId,proto3" json:"voter_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteResponse) Reset() {
	*x = RequestVoteResponse{}
	mi := &file_raft_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteResponse) ProtoMessage() {}

func (x *RequestVoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteResponse.ProtoReflect.Descriptor instead.
func (*RequestVoteResponse) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{5}
}

func (x *RequestVoteResponse) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RequestVoteResponse) GetVoteGranted() bool {
	if x != nil {
		return x.VoteGranted
	}
	return false
}

func (x *RequestVoteResponse) GetVoterId() uint64 {
	if x != nil {
		return x.VoterId
	}
	return 0
}

type HeartbeatNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId      uint64                 `protobuf:"varint,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	Commit        uint64                 `protobuf:"varint,3,opt,name=commit,proto3" json:"commit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatNotify) Reset() {
	*x = HeartbeatNotify{}
	mi := &file_raft_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatNotify) ProtoMessage() {}

func (x *HeartbeatNotify) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatNotify.ProtoReflect.Descriptor instead.
func (*HeartbeatNotify) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatNotify) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *HeartbeatNotify) GetLeaderId() uint64 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *HeartbeatNotify) GetCommit() uint64 {
	if x != nil {
		return x.Commit
	}
	return 0
}

type InstallSnapshotRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Term              uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId          uint64                 `protobuf:"varint,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	LastIncludedIndex uint64                 `protobuf:"varint,3,opt,name=last_included_index,json=lastIncludedIndex,proto3" json:"last_included_index,omitempty"`
	LastIncludedTerm  uint64                 `protobuf:"varint,4,opt,name=last_included_term,json=lastIncludedTerm,proto3" json:"last_included_term,omitempty"`
	Data              []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"` // snapshot data
	Last              bool                   `protobuf:"varint,6,opt,name=last,proto3" json:"last,omitempty"`
	Offset            uint64                 `protobuf:"varint,7,opt,name=offset,proto3" json:"offset,omitempty"` // 块偏移
	Len               uint64                 `protobuf:"varint,8,opt,name=len,proto3" json:"len,omitempty"`       // 块长度
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InstallSnapshotRequest) Reset() {
	*x = InstallSnapshotRequest{}
	mi := &file_raft_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallSnapshotRequest) ProtoMessage() {}

func (x *InstallSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallSnapshotRequest.ProtoReflect.Descriptor instead.
func (*InstallSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{7}
}

func (x *InstallSnapshotRequest) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *InstallSnapshotRequest) GetLeaderId() uint64 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *InstallSnapshotRequest) GetLastIncludedIndex() uint64 {
	if x != nil {
		return x.LastIncludedIndex
	}
	return 0
}

func (x *InstallSnapshotRequest) GetLastIncludedTerm() uint64 {
	if x != nil {
		return x.LastIncludedTerm
	}
	return 0
}

func (x *InstallSnapshotRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *InstallSnapshotRequest) GetLast() bool {
	if x != nil {
		return x.Last
	}
	return false
}

func (x *InstallSnapshotRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *InstallSnapshotRequest) GetLen() uint64 {
	if x != nil {
		return x.Len
	}
	return 0
}

type InstallSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	MsgSize       uint64                 `protobuf:"varint,2,opt,name=msg_size,json=msgSize,proto3" json:"msg_size,omitempty"` // 已接收的总大小
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallSnapshotResponse) Reset() {
	*x = InstallSnapshotResponse{}
	mi := &file_raft_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallSnapshotResponse) ProtoMessage() {}

func (x *InstallSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallSnapshotResponse.ProtoReflect.Descriptor instead.
func (*InstallSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{8}
}

func (x *InstallSnapshotResponse) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *InstallSnapshotResponse) GetMsgSize() uint64 {
	if x != nil {
		return x.MsgSize
	}
	return 0
}

func (x *InstallSnapshotResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type Snapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Metadata      *SnapshotMetadata      `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_raft_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{9}
}

func (x *Snapshot) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Snapshot) GetMetadata() *SnapshotMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SnapshotMetadata struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LastIncludedIndex uint64                 `protobuf:"varint,1,opt,name=last_included_index,json=lastIncludedIndex,proto3" json:"last_included_index,omitempty"`
	LastIncludedTerm  uint64                 `protobuf:"varint,2,opt,name=last_included_term,json=lastIncludedTerm,proto3" json:"last_included_term,omitempty"`
	Revision          int64                  `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"` // 快照时的全局 revision
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SnapshotMetadata) Reset() {
	*x = SnapshotMetadata{}
	mi := &file_raft_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotMetadata) ProtoMessage() {}

func (x *SnapshotMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_raft_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotMetadata.ProtoReflect.Descriptor instead.
func (*SnapshotMetadata) Descriptor() ([]byte, []int) {
	return file_raft_proto_rawDescGZIP(), []int{10}
}

func (x *SnapshotMetadata) GetLastIncludedIndex() uint64 {
	if x != nil {
		return x.LastIncludedIndex
	}
	return 0
}

func (x *SnapshotMetadata) GetLastIncludedTerm() uint64 {
	if x != nil {
		return x.LastIncludedTerm
	}
	return 0
}

func (x *SnapshotMetadata) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

var File_raft_proto protoreflect.FileDescriptor

const file_raft_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"raft.proto\x12\x06raftpb\"E\n" +
	"\x05Entry\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x04R\x05index\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"\xa2\x04\n" +
	"\vRaftMessage\x12'\n" +
	"\x04type\x18\x01 \x01(\x0e2\x13.raftpb.MessageTypeR\x04type\x12\x12\n" +
	"\x04from\x18\x02 \x01(\x04R\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\x04R\x02to\x12\x12\n" +
	"\x04term\x18\x04 \x01(\x04R\x04term\x12=\n" +
	"\n" +
	"append_req\x18\n" +
	" \x01(\v2\x1c.raftpb.AppendEntriesRequestH\x00R\tappendReq\x12@\n" +
	"\vappend_resp\x18\v \x01(\v2\x1d.raftpb.AppendEntriesResponseH\x00R\n" +
	"appendResp\x127\n" +
	"\bvote_req\x18\f \x01(\v2\x1a.raftpb.RequestVoteRequestH\x00R\avoteReq\x12:\n" +
	"\tvote_resp\x18\r \x01(\v2\x1b.raftpb.RequestVoteResponseH\x00R\bvoteResp\x12;\n" +
	"\bsnap_req\x18\x0e \x01(\v2\x1e.raftpb.InstallSnapshotRequestH\x00R\asnapReq\x12>\n" +
	"\tsnap_resp\x18\x0f \x01(\v2\x1f.raftpb.InstallSnapshotResponseH\x00R\bsnapResp\x127\n" +
	"\theartbeat\x18\x10 \x01(\v2\x17.raftpb.HeartbeatNotifyH\x00R\theartbeatB\x06\n" +
	"\x04body\"\xdf\x01\n" +
	"\x14AppendEntriesRequest\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\x04R\bleaderId\x12$\n" +
	"\x0eprev_log_index\x18\x03 \x01(\x04R\fprevLogIndex\x12\"\n" +
	"\rprev_log_term\x18\x04 \x01(\x04R\vprevLogTerm\x12'\n" +
	"\aentries\x18\x05 \x03(\v2\r.raftpb.EntryR\aentries\x12#\n" +
	"\rleader_commit\x18\x06 \x01(\x04R\fleaderCommit\"\x81\x01\n" +
	"\x15AppendEntriesResponse\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12\x19\n" +
	"\blast_log\x18\x02 \x01(\x04R\alastLog\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x1f\n" +
	"\vreject_hint\x18\x04 \x01(\x04R\n" +
	"rejectHint\"\x95\x01\n" +
	"\x12RequestVoteRequest\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12!\n" +
	"\fcandidate_id\x18\x02 \x01(\x04R\vcandidateId\x12$\n" +
	"\x0elast_log_index\x18\x03 \x01(\x04R\flastLogIndex\x12\"\n" +
	"\rlast_log_term\x18\x04 \x01(\x04R\vlastLogTerm\"g\n" +
	"\x13RequestVoteResponse\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12!\n" +
	"\fvote_granted\x18\x02 \x01(\bR\vvoteGranted\x12\x19\n" +
	"\bvoter_id\x18\x03 \x01(\x04R\avoterId\"Z\n" +
	"\x0fHeartbeatNotify\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\x04R\bleaderId\x12\x16\n" +
	"\x06commit\x18\x03 \x01(\x04R\x06commit\"\xf9\x01\n" +
	"\x16InstallSnapshotRequest\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\x04R\bleaderId\x12.\n" +
	"\x13last_included_index\x18\x03 \x01(\x04R\x11lastIncludedIndex\x12,\n" +
	"\x12last_included_term\x18\x04 \x01(\x04R\x10lastIncludedTerm\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\x12\x12\n" +
	"\x04last\x18\x06 \x01(\bR\x04last\x12\x16\n" +
	"\x06offset\x18\a \x01(\x04R\x06offset\x12\x10\n" +
	"\x03len\x18\b \x01(\x04R\x03len\"b\n" +
	"\x17InstallSnapshotResponse\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12\x19\n" +
	"\bmsg_size\x18\x02 \x01(\x04R\amsgSize\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\"T\n" +
	"\bSnapshot\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x124\n" +
	"\bmetadata\x18\x02 \x01(\v2\x18.raftpb.SnapshotMetadataR\bmetadata\"\x8c\x01\n" +
	"\x10SnapshotMetadata\x12.\n" +
	"\x13last_included_index\x18\x01 \x01(\x04R\x11lastIncludedIndex\x12,\n" +
	"\x12last_included_term\x18\x02 \x01(\x04R\x10lastIncludedTerm\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\x03R\brevision*\x98\x02\n" +
	"\vMessageType\x12\x1c\n" +
	"\x18MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17MESSAGE_TYPE_APPEND_REQ\x10\x01\x12\x1c\n" +
	"\x18MESSAGE_TYPE_APPEND_RESP\x10\x02\x12!\n" +
	"\x1dMESSAGE_TYPE_REQUEST_VOTE_REQ\x10\x03\x12\"\n" +
	"\x1eMESSAGE_TYPE_REQUEST_VOTE_RESP\x10\x04\x12%\n" +
	"!MESSAGE_TYPE_INSTALL_SNAPSHOT_REQ\x10\x05\x12&\n" +
	"\"MESSAGE_TYPE_INSTALL_SNAPSHOT_RESP\x10\x06\x12\x1a\n" +
	"\x16MESSAGE_TYPE_HEARTBEAT\x10\a2N\n" +
	"\rRaftTransport\x12=\n" +
	"\rStreamMessage\x12\x13.raftpb.RaftMessage\x1a\x13.raftpb.RaftMessage(\x010\x01B9Z7github.com/DecarbonizedGlucose/rkv/api/proto/pkg/raftpbb\x06proto3"

var (
	file_raft_proto_rawDescOnce sync.Once
	file_raft_proto_rawDescData []byte
)

func file_raft_proto_rawDescGZIP() []byte {
	file_raft_proto_rawDescOnce.Do(func() {
		file_raft_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_raft_proto_rawDesc), len(file_raft_proto_rawDesc)))
	})
	return file_raft_proto_rawDescData
}

var file_raft_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_raft_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_raft_proto_goTypes = []any{
	(MessageType)(0),                // 0: raftpb.MessageType
	(*Entry)(nil),                   // 1: raftpb.Entry
	(*RaftMessage)(nil),             // 2: raftpb.RaftMessage
	(*AppendEntriesRequest)(nil),    // 3: raftpb.AppendEntriesRequest
	(*AppendEntriesResponse)(nil),   // 4: raftpb.AppendEntriesResponse
	(*RequestVoteRequest)(nil),      // 5: raftpb.RequestVoteRequest
	(*RequestVoteResponse)(nil),     // 6: raftpb.RequestVoteResponse
	(*HeartbeatNotify)(nil),         // 7: raftpb.HeartbeatNotify
	(*InstallSnapshotRequest)(nil),  // 8: raftpb.InstallSnapshotRequest
	(*InstallSnapshotResponse)(nil), // 9: raftpb.InstallSnapshotResponse
	(*Snapshot)(nil),                // 10: raftpb.Snapshot
	(*SnapshotMetadata)(nil),        // 11: raftpb.SnapshotMetadata
}
var file_raft_proto_depIdxs = []int32{
	0,  // 0: raftpb.RaftMessage.type:type_name -> raftpb.MessageType
	3,  // 1: raftpb.RaftMessage.append_req:type_name -> raftpb.AppendEntriesRequest
	4,  // 2: raftpb.RaftMessage.append_resp:type_name -> raftpb.AppendEntriesResponse
	5,  // 3: raftpb.RaftMessage.vote_req:type_name -> raftpb.RequestVoteRequest
	6,  // 4: raftpb.RaftMessage.vote_resp:type_name -> raftpb.RequestVoteResponse
	8,  // 5: raftpb.RaftMessage.snap_req:type_name -> raftpb.InstallSnapshotRequest
	9,  // 6: raftpb.RaftMessage.snap_resp:type_name -> raftpb.InstallSnapshotResponse
	7,  // 7: raftpb.RaftMessage.heartbeat:type_name -> raftpb.HeartbeatNotify
	1,  // 8: raftpb.AppendEntriesRequest.entries:type_name -> raftpb.Entry
	11, // 9: raftpb.Snapshot.metadata:type_name -> raftpb.SnapshotMetadata
	2,  // 10: raftpb.RaftTransport.StreamMessage:input_type -> raftpb.RaftMessage
	2,  // 11: raftpb.RaftTransport.StreamMessage:output_type -> raftpb.RaftMessage
	11, // [11:12] is the sub-list for method output_type
	10, // [10:11] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_raft_proto_init() }
func file_raft_proto_init() {
	if File_raft_proto != nil {
		return
	}
	file_raft_proto_msgTypes[1].OneofWrappers = []any{
		(*RaftMessage_AppendReq)(nil),
		(*RaftMessage_AppendResp)(nil),
		(*RaftMessage_VoteReq)(nil),
		(*RaftMessage_VoteResp)(nil),
		(*RaftMessage_SnapReq)(nil),
		(*RaftMessage_SnapResp)(nil),
		(*RaftMessage_Heartbeat)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_raft_proto_rawDesc), len(file_raft_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_raft_proto_goTypes,
		DependencyIndexes: file_raft_proto_depIdxs,
		EnumInfos:         file_raft_proto_enumTypes,
		MessageInfos:      file_raft_proto_msgTypes,
	}.Build()
	File_raft_proto = out.File
	file_raft_proto_goTypes = nil
	file_raft_proto_depIdxs = nil
}
