// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: kv.proto

package kvpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED EventType = 0
	EventType_PUT                    EventType = 1 // 写入或更新
	EventType_DELETE                 EventType = 2 // 删除
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "PUT",
		2: "DELETE",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED": 0,
		"PUT":                    1,
		"DELETE":                 2,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_kv_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_kv_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{0}
}

type Compare_CompareResult int32

const (
	Compare_EQUAL     Compare_CompareResult = 0
	Compare_GREATER   Compare_CompareResult = 1
	Compare_LESS      Compare_CompareResult = 2
	Compare_NOT_EQUAL Compare_CompareResult = 3
)

// Enum value maps for Compare_CompareResult.
var (
	Compare_CompareResult_name = map[int32]string{
		0: "EQUAL",
		1: "GREATER",
		2: "LESS",
		3: "NOT_EQUAL",
	}
	Compare_CompareResult_value = map[string]int32{
		"EQUAL":     0,
		"GREATER":   1,
		"LESS":      2,
		"NOT_EQUAL": 3,
	}
)

func (x Compare_CompareResult) Enum() *Compare_CompareResult {
	p := new(Compare_CompareResult)
	*p = x
	return p
}

func (x Compare_CompareResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Compare_CompareResult) Descriptor() protoreflect.EnumDescriptor {
	return file_kv_proto_enumTypes[1].Descriptor()
}

func (Compare_CompareResult) Type() protoreflect.EnumType {
	return &file_kv_proto_enumTypes[1]
}

func (x Compare_CompareResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Compare_CompareResult.Descriptor instead.
func (Compare_CompareResult) EnumDescriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{11, 0}
}

type Compare_CompareTarget int32

const (
	Compare_VERSION Compare_CompareTarget = 0 // ModRevision
	Compare_CREATE  Compare_CompareTarget = 1 // CreateRevision
	Compare_VALUE   Compare_CompareTarget = 2 // Value
	Compare_LEASE   Compare_CompareTarget = 3 // LeaseID
)

// Enum value maps for Compare_CompareTarget.
var (
	Compare_CompareTarget_name = map[int32]string{
		0: "VERSION",
		1: "CREATE",
		2: "VALUE",
		3: "LEASE",
	}
	Compare_CompareTarget_value = map[string]int32{
		"VERSION": 0,
		"CREATE":  1,
		"VALUE":   2,
		"LEASE":   3,
	}
)

func (x Compare_CompareTarget) Enum() *Compare_CompareTarget {
	p := new(Compare_CompareTarget)
	*p = x
	return p
}

func (x Compare_CompareTarget) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Compare_CompareTarget) Descriptor() protoreflect.EnumDescriptor {
	return file_kv_proto_enumTypes[2].Descriptor()
}

func (Compare_CompareTarget) Type() protoreflect.EnumType {
	return &file_kv_proto_enumTypes[2]
}

func (x Compare_CompareTarget) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Compare_CompareTarget.Descriptor instead.
func (Compare_CompareTarget) EnumDescriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{11, 1}
}

type ResponseHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      uint64                 `protobuf:"varint,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"` // 节点在集群中的ID
	Revision      uint64                 `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`                 // 集群 revision
	RaftTerm      uint64                 `protobuf:"varint,3,opt,name=raft_term,json=raftTerm,proto3" json:"raft_term,omitempty"` // Raft 任期号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseHeader) Reset() {
	*x = ResponseHeader{}
	mi := &file_kv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseHeader) ProtoMessage() {}

func (x *ResponseHeader) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseHeader.ProtoReflect.Descriptor instead.
func (*ResponseHeader) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseHeader) GetMemberId() uint64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *ResponseHeader) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *ResponseHeader) GetRaftTerm() uint64 {
	if x != nil {
		return x.RaftTerm
	}
	return 0
}

type KeyValue struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Key            []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value          []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Revision       uint64                 `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`                                   // 当前 revision
	CreateRevision uint64                 `protobuf:"varint,4,opt,name=create_revision,json=createRevision,proto3" json:"create_revision,omitempty"` // 创建时的 revision
	ModRevision    uint64                 `protobuf:"varint,5,opt,name=mod_revision,json=modRevision,proto3" json:"mod_revision,omitempty"`          // 最后修改时的 revision
	LeaseId        int64                  `protobuf:"varint,6,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`                      // 关联的 LeaseID, 0 = 无
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	mi := &file_kv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{1}
}

func (x *KeyValue) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *KeyValue) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *KeyValue) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *KeyValue) GetCreateRevision() uint64 {
	if x != nil {
		return x.CreateRevision
	}
	return 0
}

func (x *KeyValue) GetModRevision() uint64 {
	if x != nil {
		return x.ModRevision
	}
	return 0
}

func (x *KeyValue) GetLeaseId() int64 {
	if x != nil {
		return x.LeaseId
	}
	return 0
}

type Command struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Op:
	//
	//	*Command_Put
	//	*Command_Delete
	//	*Command_Txn
	//	*Command_LeaseGrant
	//	*Command_LeaseRevoke
	Op            isCommand_Op `protobuf_oneof:"op"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_kv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{2}
}

func (x *Command) GetOp() isCommand_Op {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *Command) GetPut() *PutRequest {
	if x != nil {
		if x, ok := x.Op.(*Command_Put); ok {
			return x.Put
		}
	}
	return nil
}

func (x *Command) GetDelete() *DeleteRequest {
	if x != nil {
		if x, ok := x.Op.(*Command_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

func (x *Command) GetTxn() *TxnRequest {
	if x != nil {
		if x, ok := x.Op.(*Command_Txn); ok {
			return x.Txn
		}
	}
	return nil
}

func (x *Command) GetLeaseGrant() *LeaseGrantCommand {
	if x != nil {
		if x, ok := x.Op.(*Command_LeaseGrant); ok {
			return x.LeaseGrant
		}
	}
	return nil
}

func (x *Command) GetLeaseRevoke() *LeaseRevokeCommand {
	if x != nil {
		if x, ok := x.Op.(*Command_LeaseRevoke); ok {
			return x.LeaseRevoke
		}
	}
	return nil
}

type isCommand_Op interface {
	isCommand_Op()
}

type Command_Put struct {
	Put *PutRequest `protobuf:"bytes,1,opt,name=put,proto3,oneof"`
}

type Command_Delete struct {
	Delete *DeleteRequest `protobuf:"bytes,2,opt,name=delete,proto3,oneof"`
}

type Command_Txn struct {
	Txn *TxnRequest `protobuf:"bytes,3,opt,name=txn,proto3,oneof"`
}

type Command_LeaseGrant struct {
	LeaseGrant *LeaseGrantCommand `protobuf:"bytes,4,opt,name=lease_grant,json=leaseGrant,proto3,oneof"`
}

type Command_LeaseRevoke struct {
	LeaseRevoke *LeaseRevokeCommand `protobuf:"bytes,5,opt,name=lease_revoke,json=leaseRevoke,proto3,oneof"`
}

func (*Command_Put) isCommand_Op() {}

func (*Command_Delete) isCommand_Op() {}

func (*Command_Txn) isCommand_Op() {}

func (*Command_LeaseGrant) isCommand_Op() {}

func (*Command_LeaseRevoke) isCommand_Op() {}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_kv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{3}
}

func (x *GetRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *ResponseHeader        `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Kv            *KeyValue              `protobuf:"bytes,2,opt,name=kv,proto3" json:"kv,omitempty"`        // 不存在时为nil
	Count         int64                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"` // 0 或 1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_kv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{4}
}

func (x *GetResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetResponse) GetKv() *KeyValue {
	if x != nil {
		return x.Kv
	}
	return nil
}

func (x *GetResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	PrevKv        int64                  `protobuf:"varint,3,opt,name=prev_kv,json=prevKv,proto3" json:"prev_kv,omitempty"` // 是否返回修改前的 value
	Lease         int64                  `protobuf:"varint,4,opt,name=lease,proto3" json:"lease,omitempty"`                 // 关联的 LeaseID, 0 = 不关联
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_kv_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{5}
}

func (x *PutRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *PutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PutRequest) GetPrevKv() int64 {
	if x != nil {
		return x.PrevKv
	}
	return 0
}

func (x *PutRequest) GetLease() int64 {
	if x != nil {
		return x.Lease
	}
	return 0
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *ResponseHeader        `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	PrevKv        *KeyValue              `protobuf:"bytes,2,opt,name=prev_kv,json=prevKv,proto3" json:"prev_kv,omitempty"` // 修改前的 KV（如果 prev_kv=true）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_kv_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{6}
}

func (x *PutResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *PutResponse) GetPrevKv() *KeyValue {
	if x != nil {
		return x.PrevKv
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	PrevKv        int64                  `protobuf:"varint,2,opt,name=prev_kv,json=prevKv,proto3" json:"prev_kv,omitempty"` // 是否返回删除前的 value
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_kv_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *DeleteRequest) GetPrevKv() int64 {
	if x != nil {
		return x.PrevKv
	}
	return 0
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *ResponseHeader        `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Deleted       int64                  `protobuf:"varint,2,opt,name=deleted,proto3" json:"deleted,omitempty"`            // 删除的条数（0 或 1）
	PrevKv        *KeyValue              `protobuf:"bytes,3,opt,name=prev_kv,json=prevKv,proto3" json:"prev_kv,omitempty"` // 删除前的 KV（如果 prev_kv=true）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_kv_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *DeleteResponse) GetDeleted() int64 {
	if x != nil {
		return x.Deleted
	}
	return 0
}

func (x *DeleteResponse) GetPrevKv() *KeyValue {
	if x != nil {
		return x.PrevKv
	}
	return nil
}

type RangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RangeStart    []byte                 `protobuf:"bytes,1,opt,name=range_start,json=rangeStart,proto3" json:"range_start,omitempty"` // 起始 key [start, end)
	RangeEnd      []byte                 `protobuf:"bytes,2,opt,name=range_end,json=rangeEnd,proto3" json:"range_end,omitempty"`       // 结束 key，为空表示精确匹配 key
	Limit         int64                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                            // 返回上限（0 = 无限制）
	Revision      uint64                 `protobuf:"varint,4,opt,name=revision,proto3" json:"revision,omitempty"`                      // 指定 revision 读取（0 = 最新）
	KeysOnly      bool                   `protobuf:"varint,5,opt,name=keys_only,json=keysOnly,proto3" json:"keys_only,omitempty"`      // 只返回 key，不返回 value
	CountOnly     bool                   `protobuf:"varint,6,opt,name=count_only,json=countOnly,proto3" json:"count_only,omitempty"`   // 只返回计数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RangeRequest) Reset() {
	*x = RangeRequest{}
	mi := &file_kv_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeRequest) ProtoMessage() {}

func (x *RangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeRequest.ProtoReflect.Descriptor instead.
func (*RangeRequest) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{9}
}

func (x *RangeRequest) GetRangeStart() []byte {
	if x != nil {
		return x.RangeStart
	}
	return nil
}

func (x *RangeRequest) GetRangeEnd() []byte {
	if x != nil {
		return x.RangeEnd
	}
	return nil
}

func (x *RangeRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *RangeRequest) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *RangeRequest) GetKeysOnly() bool {
	if x != nil {
		return x.KeysOnly
	}
	return false
}

func (x *RangeRequest) GetCountOnly() bool {
	if x != nil {
		return x.CountOnly
	}
	return false
}

type RangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *ResponseHeader        `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Kvs           []*KeyValue            `protobuf:"bytes,2,rep,name=kvs,proto3" json:"kvs,omitempty"`
	Count         int64                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	More          bool                   `protobuf:"varint,4,opt,name=more,proto3" json:"more,omitempty"` // 是否有 limit 外的更多？
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RangeResponse) Reset() {
	*x = RangeResponse{}
	mi := &file_kv_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeResponse) ProtoMessage() {}

func (x *RangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeResponse.ProtoReflect.Descriptor instead.
func (*RangeResponse) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{10}
}

func (x *RangeResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *RangeResponse) GetKvs() []*KeyValue {
	if x != nil {
		return x.Kvs
	}
	return nil
}

func (x *RangeResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *RangeResponse) GetMore() bool {
	if x != nil {
		return x.More
	}
	return false
}

type Compare struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Result Compare_CompareResult  `protobuf:"varint,1,opt,name=result,proto3,enum=kvpb.Compare_CompareResult" json:"result,omitempty"`
	Target Compare_CompareTarget  `protobuf:"varint,2,opt,name=target,proto3,enum=kvpb.Compare_CompareTarget" json:"target,omitempty"`
	Key    []byte                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	// Types that are valid to be assigned to TargetValue:
	//
	//	*Compare_Version
	//	*Compare_Value
	TargetValue   isCompare_TargetValue `protobuf_oneof:"target_value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Compare) Reset() {
	*x = Compare{}
	mi := &file_kv_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Compare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Compare) ProtoMessage() {}

func (x *Compare) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Compare.ProtoReflect.Descriptor instead.
func (*Compare) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{11}
}

func (x *Compare) GetResult() Compare_CompareResult {
	if x != nil {
		return x.Result
	}
	return Compare_EQUAL
}

func (x *Compare) GetTarget() Compare_CompareTarget {
	if x != nil {
		return x.Target
	}
	return Compare_VERSION
}

func (x *Compare) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Compare) GetTargetValue() isCompare_TargetValue {
	if x != nil {
		return x.TargetValue
	}
	return nil
}

func (x *Compare) GetVersion() uint64 {
	if x != nil {
		if x, ok := x.TargetValue.(*Compare_Version); ok {
			return x.Version
		}
	}
	return 0
}

func (x *Compare) GetValue() []byte {
	if x != nil {
		if x, ok := x.TargetValue.(*Compare_Value); ok {
			return x.Value
		}
	}
	return nil
}

type isCompare_TargetValue interface {
	isCompare_TargetValue()
}

type Compare_Version struct {
	Version uint64 `protobuf:"varint,4,opt,name=version,proto3,oneof"` // revision / lease
}

type Compare_Value struct {
	Value []byte `protobuf:"bytes,5,opt,name=value,proto3,oneof"` // value
}

func (*Compare_Version) isCompare_TargetValue() {}

func (*Compare_Value) isCompare_TargetValue() {}

type RequestOp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*RequestOp_Put
	//	*RequestOp_Delete
	//	*RequestOp_Range
	Request       isRequestOp_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestOp) Reset() {
	*x = RequestOp{}
	mi := &file_kv_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestOp) ProtoMessage() {}

func (x *RequestOp) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestOp.ProtoReflect.Descriptor instead.
func (*RequestOp) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{12}
}

func (x *RequestOp) GetRequest() isRequestOp_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *RequestOp) GetPut() *PutRequest {
	if x != nil {
		if x, ok := x.Request.(*RequestOp_Put); ok {
			return x.Put
		}
	}
	return nil
}

func (x *RequestOp) GetDelete() *DeleteRequest {
	if x != nil {
		if x, ok := x.Request.(*RequestOp_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

func (x *RequestOp) GetRange() *RangeRequest {
	if x != nil {
		if x, ok := x.Request.(*RequestOp_Range); ok {
			return x.Range
		}
	}
	return nil
}

type isRequestOp_Request interface {
	isRequestOp_Request()
}

type RequestOp_Put struct {
	Put *PutRequest `protobuf:"bytes,1,opt,name=put,proto3,oneof"`
}

type RequestOp_Delete struct {
	Delete *DeleteRequest `protobuf:"bytes,2,opt,name=delete,proto3,oneof"`
}

type RequestOp_Range struct {
	Range *RangeRequest `protobuf:"bytes,3,opt,name=range,proto3,oneof"`
}

func (*RequestOp_Put) isRequestOp_Request() {}

func (*RequestOp_Delete) isRequestOp_Request() {}

func (*RequestOp_Range) isRequestOp_Request() {}

type ResponseOp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*ResponseOp_Put
	//	*ResponseOp_Delete
	//	*ResponseOp_Range
	Response      isResponseOp_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseOp) Reset() {
	*x = ResponseOp{}
	mi := &file_kv_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseOp) ProtoMessage() {}

func (x *ResponseOp) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseOp.ProtoReflect.Descriptor instead.
func (*ResponseOp) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{13}
}

func (x *ResponseOp) GetResponse() isResponseOp_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *ResponseOp) GetPut() *PutResponse {
	if x != nil {
		if x, ok := x.Response.(*ResponseOp_Put); ok {
			return x.Put
		}
	}
	return nil
}

func (x *ResponseOp) GetDelete() *DeleteResponse {
	if x != nil {
		if x, ok := x.Response.(*ResponseOp_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

func (x *ResponseOp) GetRange() *RangeResponse {
	if x != nil {
		if x, ok := x.Response.(*ResponseOp_Range); ok {
			return x.Range
		}
	}
	return nil
}

type isResponseOp_Response interface {
	isResponseOp_Response()
}

type ResponseOp_Put struct {
	Put *PutResponse `protobuf:"bytes,1,opt,name=put,proto3,oneof"`
}

type ResponseOp_Delete struct {
	Delete *DeleteResponse `protobuf:"bytes,2,opt,name=delete,proto3,oneof"`
}

type ResponseOp_Range struct {
	Range *RangeResponse `protobuf:"bytes,3,opt,name=range,proto3,oneof"`
}

func (*ResponseOp_Put) isResponseOp_Response() {}

func (*ResponseOp_Delete) isResponseOp_Response() {}

func (*ResponseOp_Range) isResponseOp_Response() {}

type TxnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Compares      []*Compare             `protobuf:"bytes,1,rep,name=compares,proto3" json:"compares,omitempty"`
	Success       []*RequestOp           `protobuf:"bytes,2,rep,name=success,proto3" json:"success,omitempty"`
	Failure       []*RequestOp           `protobuf:"bytes,3,rep,name=failure,proto3" json:"failure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxnRequest) Reset() {
	*x = TxnRequest{}
	mi := &file_kv_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnRequest) ProtoMessage() {}

func (x *TxnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnRequest.ProtoReflect.Descriptor instead.
func (*TxnRequest) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{14}
}

func (x *TxnRequest) GetCompares() []*Compare {
	if x != nil {
		return x.Compares
	}
	return nil
}

func (x *TxnRequest) GetSuccess() []*RequestOp {
	if x != nil {
		return x.Success
	}
	return nil
}

func (x *TxnRequest) GetFailure() []*RequestOp {
	if x != nil {
		return x.Failure
	}
	return nil
}

type TxnResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *ResponseHeader        `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Succeeded     bool                   `protobuf:"varint,2,opt,name=succeeded,proto3" json:"succeeded,omitempty"` // 条件是否满足
	Responses     []*ResponseOp          `protobuf:"bytes,3,rep,name=responses,proto3" json:"responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxnResponse) Reset() {
	*x = TxnResponse{}
	mi := &file_kv_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnResponse) ProtoMessage() {}

func (x *TxnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnResponse.ProtoReflect.Descriptor instead.
func (*TxnResponse) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{15}
}

func (x *TxnResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *TxnResponse) GetSucceeded() bool {
	if x != nil {
		return x.Succeeded
	}
	return false
}

func (x *TxnResponse) GetResponses() []*ResponseOp {
	if x != nil {
		return x.Responses
	}
	return nil
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          EventType              `protobuf:"varint,1,opt,name=type,proto3,enum=kvpb.EventType" json:"type,omitempty"`
	Kv            *KeyValue              `protobuf:"bytes,2,opt,name=kv,proto3" json:"kv,omitempty"`                       // 当前 KV
	PrevKv        *KeyValue              `protobuf:"bytes,3,opt,name=prev_kv,json=prevKv,proto3" json:"prev_kv,omitempty"` // 修改前的 KV, 删除时非空, Put 时可选
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_kv_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{16}
}

func (x *Event) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *Event) GetKv() *KeyValue {
	if x != nil {
		return x.Kv
	}
	return nil
}

func (x *Event) GetPrevKv() *KeyValue {
	if x != nil {
		return x.PrevKv
	}
	return nil
}

type WatchRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Key            []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Prefix         bool                   `protobuf:"varint,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	StartRevision  int64                  `protobuf:"varint,3,opt,name=start_revision,json=startRevision,proto3" json:"start_revision,omitempty"`
	PrevKv         bool                   `protobuf:"varint,4,opt,name=prev_kv,json=prevKv,proto3" json:"prev_kv,omitempty"`
	ProgressNotify bool                   `protobuf:"varint,5,opt,name=progress_notify,json=progressNotify,proto3" json:"progress_notify,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_kv_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{17}
}

func (x *WatchRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *WatchRequest) GetPrefix() bool {
	if x != nil {
		return x.Prefix
	}
	return false
}

func (x *WatchRequest) GetStartRevision() int64 {
	if x != nil {
		return x.StartRevision
	}
	return 0
}

func (x *WatchRequest) GetPrevKv() bool {
	if x != nil {
		return x.PrevKv
	}
	return false
}

func (x *WatchRequest) GetProgressNotify() bool {
	if x != nil {
		return x.ProgressNotify
	}
	return false
}

type WatchResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Header          *ResponseHeader        `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	WatchId         int64                  `protobuf:"varint,2,opt,name=watch_id,json=watchId,proto3" json:"watch_id,omitempty"`
	Created         bool                   `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	Canceled        bool                   `protobuf:"varint,4,opt,name=canceled,proto3" json:"canceled,omitempty"`
	CompactRevision int64                  `protobuf:"varint,5,opt,name=compact_revision,json=compactRevision,proto3" json:"compact_revision,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WatchResponse) Reset() {
	*x = WatchResponse{}
	mi := &file_kv_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchResponse) ProtoMessage() {}

func (x *WatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchResponse.ProtoReflect.Descriptor instead.
func (*WatchResponse) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{18}
}

func (x *WatchResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *WatchResponse) GetWatchId() int64 {
	if x != nil {
		return x.WatchId
	}
	return 0
}

func (x *WatchResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

func (x *WatchResponse) GetCanceled() bool {
	if x != nil {
		return x.Canceled
	}
	return false
}

func (x *WatchResponse) GetCompactRevision() int64 {
	if x != nil {
		return x.CompactRevision
	}
	return 0
}

type LeaseGrantCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`   // 预分配 LeaseID
	Ttl           int64                  `protobuf:"varint,2,opt,name=ttl,proto3" json:"ttl,omitempty"` // TTL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseGrantCommand) Reset() {
	*x = LeaseGrantCommand{}
	mi := &file_kv_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseGrantCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseGrantCommand) ProtoMessage() {}

func (x *LeaseGrantCommand) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseGrantCommand.ProtoReflect.Descriptor instead.
func (*LeaseGrantCommand) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{19}
}

func (x *LeaseGrantCommand) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LeaseGrantCommand) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

type LeaseRevokeCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // LeaseID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseRevokeCommand) Reset() {
	*x = LeaseRevokeCommand{}
	mi := &file_kv_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseRevokeCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseRevokeCommand) ProtoMessage() {}

func (x *LeaseRevokeCommand) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseRevokeCommand.ProtoReflect.Descriptor instead.
func (*LeaseRevokeCommand) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{20}
}

func (x *LeaseRevokeCommand) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type LeaseGrantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ttl           int64                  `protobuf:"varint,1,opt,name=ttl,proto3" json:"ttl,omitempty"` // TTL
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`   // 请求的 LeaseID, 0 = 自动分配
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseGrantRequest) Reset() {
	*x = LeaseGrantRequest{}
	mi := &file_kv_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseGrantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseGrantRequest) ProtoMessage() {}

func (x *LeaseGrantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseGrantRequest.ProtoReflect.Descriptor instead.
func (*LeaseGrantRequest) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{21}
}

func (x *LeaseGrantRequest) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *LeaseGrantRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type LeaseGrantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *ResponseHeader        `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`   // 分配的 LeaseID
	Ttl           int64                  `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"` // 实际 TTL
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseGrantResponse) Reset() {
	*x = LeaseGrantResponse{}
	mi := &file_kv_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseGrantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseGrantResponse) ProtoMessage() {}

func (x *LeaseGrantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseGrantResponse.ProtoReflect.Descriptor instead.
func (*LeaseGrantResponse) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{22}
}

func (x *LeaseGrantResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *LeaseGrantResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LeaseGrantResponse) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *LeaseGrantResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type LeaseRevokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseRevokeRequest) Reset() {
	*x = LeaseRevokeRequest{}
	mi := &file_kv_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseRevokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseRevokeRequest) ProtoMessage() {}

func (x *LeaseRevokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseRevokeRequest.ProtoReflect.Descriptor instead.
func (*LeaseRevokeRequest) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{23}
}

func (x *LeaseRevokeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type LeaseRevokeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *ResponseHeader        `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseRevokeResponse) Reset() {
	*x = LeaseRevokeResponse{}
	mi := &file_kv_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseRevokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseRevokeResponse) ProtoMessage() {}

func (x *LeaseRevokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseRevokeResponse.ProtoReflect.Descriptor instead.
func (*LeaseRevokeResponse) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{24}
}

func (x *LeaseRevokeResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

type LeaseKeepAliveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseKeepAliveRequest) Reset() {
	*x = LeaseKeepAliveRequest{}
	mi := &file_kv_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseKeepAliveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseKeepAliveRequest) ProtoMessage() {}

func (x *LeaseKeepAliveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseKeepAliveRequest.ProtoReflect.Descriptor instead.
func (*LeaseKeepAliveRequest) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{25}
}

func (x *LeaseKeepAliveRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type LeaseKeepAliveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *ResponseHeader        `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`   // LeaseID
	Ttl           int64                  `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"` // 续约后的 TTL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseKeepAliveResponse) Reset() {
	*x = LeaseKeepAliveResponse{}
	mi := &file_kv_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseKeepAliveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseKeepAliveResponse) ProtoMessage() {}

func (x *LeaseKeepAliveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseKeepAliveResponse.ProtoReflect.Descriptor instead.
func (*LeaseKeepAliveResponse) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{26}
}

func (x *LeaseKeepAliveResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *LeaseKeepAliveResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LeaseKeepAliveResponse) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

var File_kv_proto protoreflect.FileDescriptor

const file_kv_proto_rawDesc = "" +
	"\n" +
	"\bkv.proto\x12\x04kvpb\"f\n" +
	"\x0eResponseHeader\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\x04R\bmemberId\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x04R\brevision\x12\x1b\n" +
	"\traft_term\x18\x03 \x01(\x04R\braftTerm\"\xb5\x01\n" +
	"\bKeyValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\x04R\brevision\x12'\n" +
	"\x0fcreate_revision\x18\x04 \x01(\x04R\x0ecreateRevision\x12!\n" +
	"\fmod_revision\x18\x05 \x01(\x04R\vmodRevision\x12\x19\n" +
	"\blease_id\x18\x06 \x01(\x03R\aleaseId\"\x85\x02\n" +
	"\aCommand\x12$\n" +
	"\x03put\x18\x01 \x01(\v2\x10.kvpb.PutRequestH\x00R\x03put\x12-\n" +
	"\x06delete\x18\x02 \x01(\v2\x13.kvpb.DeleteRequestH\x00R\x06delete\x12$\n" +
	"\x03txn\x18\x03 \x01(\v2\x10.kvpb.TxnRequestH\x00R\x03txn\x12:\n" +
	"\vlease_grant\x18\x04 \x01(\v2\x17.kvpb.LeaseGrantCommandH\x00R\n" +
	"leaseGrant\x12=\n" +
	"\flease_revoke\x18\x05 \x01(\v2\x18.kvpb.LeaseRevokeCommandH\x00R\vleaseRevokeB\x04\n" +
	"\x02op\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\"q\n" +
	"\vGetResponse\x12,\n" +
	"\x06header\x18\x01 \x01(\v2\x14.kvpb.ResponseHeaderR\x06header\x12\x1e\n" +
	"\x02kv\x18\x02 \x01(\v2\x0e.kvpb.KeyValueR\x02kv\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x03R\x05count\"c\n" +
	"\n" +
	"PutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x17\n" +
	"\aprev_kv\x18\x03 \x01(\x03R\x06prevKv\x12\x14\n" +
	"\x05lease\x18\x04 \x01(\x03R\x05lease\"d\n" +
	"\vPutResponse\x12,\n" +
	"\x06header\x18\x01 \x01(\v2\x14.kvpb.ResponseHeaderR\x06header\x12'\n" +
	"\aprev_kv\x18\x02 \x01(\v2\x0e.kvpb.KeyValueR\x06prevKv\":\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x17\n" +
	"\aprev_kv\x18\x02 \x01(\x03R\x06prevKv\"\x81\x01\n" +
	"\x0eDeleteResponse\x12,\n" +
	"\x06header\x18\x01 \x01(\v2\x14.kvpb.ResponseHeaderR\x06header\x12\x18\n" +
	"\adeleted\x18\x02 \x01(\x03R\adeleted\x12'\n" +
	"\aprev_kv\x18\x03 \x01(\v2\x0e.kvpb.KeyValueR\x06prevKv\"\xba\x01\n" +
	"\fRangeRequest\x12\x1f\n" +
	"\vrange_start\x18\x01 \x01(\fR\n" +
	"rangeStart\x12\x1b\n" +
	"\trange_end\x18\x02 \x01(\fR\brangeEnd\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\x12\x1a\n" +
	"\brevision\x18\x04 \x01(\x04R\brevision\x12\x1b\n" +
	"\tkeys_only\x18\x05 \x01(\bR\bkeysOnly\x12\x1d\n" +
	"\n" +
	"count_only\x18\x06 \x01(\bR\tcountOnly\"\x89\x01\n" +
	"\rRangeResponse\x12,\n" +
	"\x06header\x18\x01 \x01(\v2\x14.kvpb.ResponseHeaderR\x06header\x12 \n" +
	"\x03kvs\x18\x02 \x03(\v2\x0e.kvpb.KeyValueR\x03kvs\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x03R\x05count\x12\x12\n" +
	"\x04more\x18\x04 \x01(\bR\x04more\"\xcb\x02\n" +
	"\aCompare\x123\n" +
	"\x06result\x18\x01 \x01(\x0e2\x1b.kvpb.Compare.CompareResultR\x06result\x123\n" +
	"\x06target\x18\x02 \x01(\x0e2\x1b.kvpb.Compare.CompareTargetR\x06target\x12\x10\n" +
	"\x03key\x18\x03 \x01(\fR\x03key\x12\x1a\n" +
	"\aversion\x18\x04 \x01(\x04H\x00R\aversion\x12\x16\n" +
	"\x05value\x18\x05 \x01(\fH\x00R\x05value\"@\n" +
	"\rCompareResult\x12\t\n" +
	"\x05EQUAL\x10\x00\x12\v\n" +
	"\aGREATER\x10\x01\x12\b\n" +
	"\x04LESS\x10\x02\x12\r\n" +
	"\tNOT_EQUAL\x10\x03\">\n" +
	"\rCompareTarget\x12\v\n" +
	"\aVERSION\x10\x00\x12\n" +
	"\n" +
	"\x06CREATE\x10\x01\x12\t\n" +
	"\x05VALUE\x10\x02\x12\t\n" +
	"\x05LEASE\x10\x03B\x0e\n" +
	"\ftarget_value\"\x97\x01\n" +
	"\tRequestOp\x12$\n" +
	"\x03put\x18\x01 \x01(\v2\x10.kvpb.PutRequestH\x00R\x03put\x12-\n" +
	"\x06delete\x18\x02 \x01(\v2\x13.kvpb.DeleteRequestH\x00R\x06delete\x12*\n" +
	"\x05range\x18\x03 \x01(\v2\x12.kvpb.RangeRequestH\x00R\x05rangeB\t\n" +
	"\arequest\"\x9c\x01\n" +
	"\n" +
	"ResponseOp\x12%\n" +
	"\x03put\x18\x01 \x01(\v2\x11.kvpb.PutResponseH\x00R\x03put\x12.\n" +
	"\x06delete\x18\x02 \x01(\v2\x14.kvpb.DeleteResponseH\x00R\x06delete\x12+\n" +
	"\x05range\x18\x03 \x01(\v2\x13.kvpb.RangeResponseH\x00R\x05rangeB\n" +
	"\n" +
	"\bresponse\"\x8d\x01\n" +
	"\n" +
	"TxnRequest\x12)\n" +
	"\bcompares\x18\x01 \x03(\v2\r.kvpb.CompareR\bcompares\x12)\n" +
	"\asuccess\x18\x02 \x03(\v2\x0f.kvpb.RequestOpR\asuccess\x12)\n" +
	"\afailure\x18\x03 \x03(\v2\x0f.kvpb.RequestOpR\afailure\"\x89\x01\n" +
	"\vTxnResponse\x12,\n" +
	"\x06header\x18\x01 \x01(\v2\x14.kvpb.ResponseHeaderR\x06header\x12\x1c\n" +
	"\tsucceeded\x18\x02 \x01(\bR\tsucceeded\x12.\n" +
	"\tresponses\x18\x03 \x03(\v2\x10.kvpb.ResponseOpR\tresponses\"u\n" +
	"\x05Event\x12#\n" +
	"\x04type\x18\x01 \x01(\x0e2\x0f.kvpb.EventTypeR\x04type\x12\x1e\n" +
	"\x02kv\x18\x02 \x01(\v2\x0e.kvpb.KeyValueR\x02kv\x12'\n" +
	"\aprev_kv\x18\x03 \x01(\v2\x0e.kvpb.KeyValueR\x06prevKv\"\xa1\x01\n" +
	"\fWatchRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\bR\x06prefix\x12%\n" +
	"\x0estart_revision\x18\x03 \x01(\x03R\rstartRevision\x12\x17\n" +
	"\aprev_kv\x18\x04 \x01(\bR\x06prevKv\x12'\n" +
	"\x0fprogress_notify\x18\x05 \x01(\bR\x0eprogressNotify\"\xb9\x01\n" +
	"\rWatchResponse\x12,\n" +
	"\x06header\x18\x01 \x01(\v2\x14.kvpb.ResponseHeaderR\x06header\x12\x19\n" +
	"\bwatch_id\x18\x02 \x01(\x03R\awatchId\x12\x18\n" +
	"\acreated\x18\x03 \x01(\bR\acreated\x12\x1a\n" +
	"\bcanceled\x18\x04 \x01(\bR\bcanceled\x12)\n" +
	"\x10compact_revision\x18\x05 \x01(\x03R\x0fcompactRevision\"5\n" +
	"\x11LeaseGrantCommand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03ttl\x18\x02 \x01(\x03R\x03ttl\"$\n" +
	"\x12LeaseRevokeCommand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"5\n" +
	"\x11LeaseGrantRequest\x12\x10\n" +
	"\x03ttl\x18\x01 \x01(\x03R\x03ttl\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\"z\n" +
	"\x12LeaseGrantResponse\x12,\n" +
	"\x06header\x18\x01 \x01(\v2\x14.kvpb.ResponseHeaderR\x06header\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\x12\x10\n" +
	"\x03ttl\x18\x03 \x01(\x03R\x03ttl\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"$\n" +
	"\x12LeaseRevokeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"C\n" +
	"\x13LeaseRevokeResponse\x12,\n" +
	"\x06header\x18\x01 \x01(\v2\x14.kvpb.ResponseHeaderR\x06header\"'\n" +
	"\x15LeaseKeepAliveRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"h\n" +
	"\x16LeaseKeepAliveResponse\x12,\n" +
	"\x06header\x18\x01 \x01(\v2\x14.kvpb.ResponseHeaderR\x06header\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\x12\x10\n" +
	"\x03ttl\x18\x03 \x01(\x03R\x03ttl*<\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03PUT\x10\x01\x12\n" +
	"\n" +
	"\x06DELETE\x10\x02B7Z5github.com/DecarbonizedGlucose/rkv/api/proto/pkg/kvpbb\x06proto3"

var (
	file_kv_proto_rawDescOnce sync.Once
	file_kv_proto_rawDescData []byte
)

func file_kv_proto_rawDescGZIP() []byte {
	file_kv_proto_rawDescOnce.Do(func() {
		file_kv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kv_proto_rawDesc), len(file_kv_proto_rawDesc)))
	})
	return file_kv_proto_rawDescData
}

var file_kv_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_kv_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_kv_proto_goTypes = []any{
	(EventType)(0),                 // 0: kvpb.EventType
	(Compare_CompareResult)(0),     // 1: kvpb.Compare.CompareResult
	(Compare_CompareTarget)(0),     // 2: kvpb.Compare.CompareTarget
	(*ResponseHeader)(nil),         // 3: kvpb.ResponseHeader
	(*KeyValue)(nil),               // 4: kvpb.KeyValue
	(*Command)(nil),                // 5: kvpb.Command
	(*GetRequest)(nil),             // 6: kvpb.GetRequest
	(*GetResponse)(nil),            // 7: kvpb.GetResponse
	(*PutRequest)(nil),             // 8: kvpb.PutRequest
	(*PutResponse)(nil),            // 9: kvpb.PutResponse
	(*DeleteRequest)(nil),          // 10: kvpb.DeleteRequest
	(*DeleteResponse)(nil),         // 11: kvpb.DeleteResponse
	(*RangeRequest)(nil),           // 12: kvpb.RangeRequest
	(*RangeResponse)(nil),          // 13: kvpb.RangeResponse
	(*Compare)(nil),                // 14: kvpb.Compare
	(*RequestOp)(nil),              // 15: kvpb.RequestOp
	(*ResponseOp)(nil),             // 16: kvpb.ResponseOp
	(*TxnRequest)(nil),             // 17: kvpb.TxnRequest
	(*TxnResponse)(nil),            // 18: kvpb.TxnResponse
	(*Event)(nil),                  // 19: kvpb.Event
	(*WatchRequest)(nil),           // 20: kvpb.WatchRequest
	(*WatchResponse)(nil),          // 21: kvpb.WatchResponse
	(*LeaseGrantCommand)(nil),      // 22: kvpb.LeaseGrantCommand
	(*LeaseRevokeCommand)(nil),     // 23: kvpb.LeaseRevokeCommand
	(*LeaseGrantRequest)(nil),      // 24: kvpb.LeaseGrantRequest
	(*LeaseGrantResponse)(nil),     // 25: kvpb.LeaseGrantResponse
	(*LeaseRevokeRequest)(nil),     // 26: kvpb.LeaseRevokeRequest
	(*LeaseRevokeResponse)(nil),    // 27: kvpb.LeaseRevokeResponse
	(*LeaseKeepAliveRequest)(nil),  // 28: kvpb.LeaseKeepAliveRequest
	(*LeaseKeepAliveResponse)(nil), // 29: kvpb.LeaseKeepAliveResponse
}
var file_kv_proto_depIdxs = []int32{
	8,  // 0: kvpb.Command.put:type_name -> kvpb.PutRequest
	10, // 1: kvpb.Command.delete:type_name -> kvpb.DeleteRequest
	17, // 2: kvpb.Command.txn:type_name -> kvpb.TxnRequest
	22, // 3: kvpb.Command.lease_grant:type_name -> kvpb.LeaseGrantCommand
	23, // 4: kvpb.Command.lease_revoke:type_name -> kvpb.LeaseRevokeCommand
	3,  // 5: kvpb.GetResponse.header:type_name -> kvpb.ResponseHeader
	4,  // 6: kvpb.GetResponse.kv:type_name -> kvpb.KeyValue
	3,  // 7: kvpb.PutResponse.header:type_name -> kvpb.ResponseHeader
	4,  // 8: kvpb.PutResponse.prev_kv:type_name -> kvpb.KeyValue
	3,  // 9: kvpb.DeleteResponse.header:type_name -> kvpb.ResponseHeader
	4,  // 10: kvpb.DeleteResponse.prev_kv:type_name -> kvpb.KeyValue
	3,  // 11: kvpb.RangeResponse.header:type_name -> kvpb.ResponseHeader
	4,  // 12: kvpb.RangeResponse.kvs:type_name -> kvpb.KeyValue
	1,  // 13: kvpb.Compare.result:type_name -> kvpb.Compare.CompareResult
	2,  // 14: kvpb.Compare.target:type_name -> kvpb.Compare.CompareTarget
	8,  // 15: kvpb.RequestOp.put:type_name -> kvpb.PutRequest
	10, // 16: kvpb.RequestOp.delete:type_name -> kvpb.DeleteRequest
	12, // 17: kvpb.RequestOp.range:type_name -> kvpb.RangeRequest
	9,  // 18: kvpb.ResponseOp.put:type_name -> kvpb.PutResponse
	11, // 19: kvpb.ResponseOp.delete:type_name -> kvpb.DeleteResponse
	13, // 20: kvpb.ResponseOp.range:type_name -> kvpb.RangeResponse
	14, // 21: kvpb.TxnRequest.compares:type_name -> kvpb.Compare
	15, // 22: kvpb.TxnRequest.success:type_name -> kvpb.RequestOp
	15, // 23: kvpb.TxnRequest.failure:type_name -> kvpb.RequestOp
	3,  // 24: kvpb.TxnResponse.header:type_name -> kvpb.ResponseHeader
	16, // 25: kvpb.TxnResponse.responses:type_name -> kvpb.ResponseOp
	0,  // 26: kvpb.Event.type:type_name -> kvpb.EventType
	4,  // 27: kvpb.Event.kv:type_name -> kvpb.KeyValue
	4,  // 28: kvpb.Event.prev_kv:type_name -> kvpb.KeyValue
	3,  // 29: kvpb.WatchResponse.header:type_name -> kvpb.ResponseHeader
	3,  // 30: kvpb.LeaseGrantResponse.header:type_name -> kvpb.ResponseHeader
	3,  // 31: kvpb.LeaseRevokeResponse.header:type_name -> kvpb.ResponseHeader
	3,  // 32: kvpb.LeaseKeepAliveResponse.header:type_name -> kvpb.ResponseHeader
	33, // [33:33] is the sub-list for method output_type
	33, // [33:33] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_kv_proto_init() }
func file_kv_proto_init() {
	if File_kv_proto != nil {
		return
	}
	file_kv_proto_msgTypes[2].OneofWrappers = []any{
		(*Command_Put)(nil),
		(*Command_Delete)(nil),
		(*Command_Txn)(nil),
		(*Command_LeaseGrant)(nil),
		(*Command_LeaseRevoke)(nil),
	}
	file_kv_proto_msgTypes[11].OneofWrappers = []any{
		(*Compare_Version)(nil),
		(*Compare_Value)(nil),
	}
	file_kv_proto_msgTypes[12].OneofWrappers = []any{
		(*RequestOp_Put)(nil),
		(*RequestOp_Delete)(nil),
		(*RequestOp_Range)(nil),
	}
	file_kv_proto_msgTypes[13].OneofWrappers = []any{
		(*ResponseOp_Put)(nil),
		(*ResponseOp_Delete)(nil),
		(*ResponseOp_Range)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kv_proto_rawDesc), len(file_kv_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kv_proto_goTypes,
		DependencyIndexes: file_kv_proto_depIdxs,
		EnumInfos:         file_kv_proto_enumTypes,
		MessageInfos:      file_kv_proto_msgTypes,
	}.Build()
	File_kv_proto = out.File
	file_kv_proto_goTypes = nil
	file_kv_proto_depIdxs = nil
}
